"""Generate the stakeholder-facing brochure for School Tutor.

Produces two artefacts under ``docs/marketing/``:

- ``platform_overview.pdf`` — multi-page A4 brochure that walks through every
  role, feature, content type, and analytics capability.
- ``feature_map.png`` — single-page landscape infographic for slide decks
  and emails.

Run from the repo root::

    .venv/Scripts/python.exe scripts/generate_platform_brochure.py

Both files are deterministic — re-run after changing the ``CONTENT`` block to
refresh both artefacts. The data lives in this script (not in the database)
so that the brochure can be produced offline and stays in lockstep with code.
"""
from __future__ import annotations

import textwrap
from datetime import date
from pathlib import Path

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Image,
    KeepTogether,
    ListFlowable,
    ListItem,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "docs" / "marketing"
SCREENSHOTS_DIR = OUT_DIR / "screenshots"
PDF_PATH = OUT_DIR / "platform_overview.pdf"
PNG_PATH = OUT_DIR / "feature_map.png"


# ---------- Content (single source of truth — edit here, re-run script) -----


PRIMARY_HEX = "#3b82f6"          # blue
PRIMARY_DARK_HEX = "#1e3a8a"     # navy
ACCENT_HEX = "#22c55e"            # green
WARN_HEX = "#f97316"              # amber
MUTED_HEX = "#475569"             # slate
SOFT_BG_HEX = "#eef2ff"           # indigo-50
CARD_BG_HEX = "#f8fafc"           # slate-50


TAGLINE = "AI-powered CBSE / NCERT learning, ready for schools and self-learners."

EXECUTIVE_SUMMARY = (
    "School Tutor is a CBSE/NCERT-aligned platform that turns the official textbook "
    "into a complete learning environment — interactive content, practice quizzes, "
    "personalised analytics, and an AI tutor — usable by an entire school or by an "
    "individual learner. Content is generated by an LLM against the actual chapter "
    "text, curated by a small platform team, and then served as a polished, "
    "exam-aligned catalog to every classroom. Schools and individuals consume the "
    "same library; teachers assemble assessments from a quality-controlled question "
    "bank; students get instant feedback, weak-topic insights, and chapter-scoped "
    "AI help."
)


# Each role is a column in the feature map and a section in the PDF.
# `features`        — full descriptions, used in the PDF.
# `short_features`  — terse bullets (≤ ~55 chars each) used in the PNG card,
#                     because matplotlib doesn't auto-wrap text in `ax.text`.
ROLES = [
    {
        "key": "platform_admin",
        "name": "Platform admin",
        "color": "#6366f1",        # indigo
        "subtitle": "Catalog curators",
        "features": [
            "Generate AI content per chapter (worksheets, lesson plans, PPT outlines, diagrams, simulations, mind maps, flow diagrams, classroom activities, resource lists, chapter summaries).",
            "Curate the question bank — approve, reject, or restore AI-drafted questions before they reach students.",
            "Browse the full NCERT curriculum: classes, subjects, chapters, learning outcomes, source text.",
            "Tenant management — list every onboarded school and individual learner, drill into each, disable a tenant in one click (cascades to all its users).",
            "Toggle the premium AI tutor entitlement per individual learner.",
        ],
        "short_features": [
            "Generate AI content per chapter",
            "Curate question bank (approve / reject)",
            "Browse full NCERT curriculum",
            "Onboard, monitor, disable tenants",
        ],
    },
    {
        "key": "school_admin",
        "name": "School admin",
        "color": "#0ea5e9",        # sky
        "subtitle": "Tenant operator",
        "features": [
            "Edit school details, brand, contact info.",
            "Create sections, set class teachers, onboard teachers and students with login credentials.",
            "Assign teachers to specific subjects (strict scoping — teachers only see what they teach).",
            "Cross-class school report: leaderboards, average mastery, weak-topic roll-up across every section.",
            "Class-wise weak topics broken down by Factual / Understanding / Application — pinpoints exactly where to focus.",
        ],
        "short_features": [
            "Onboard sections, teachers, students",
            "Assign subjects per teacher (strict)",
            "Cross-class school performance report",
            "Class-wide weak topics by cognitive level",
        ],
    },
    {
        "key": "teacher",
        "name": "Teacher",
        "color": "#14b8a6",        # teal
        "subtitle": "Classroom lead",
        "features": [
            "Dashboard with weak topics for the classes they teach, broken down by cognitive level.",
            "Learn tab scoped to assigned subjects — chapters, topics, summaries, mind maps, simulations.",
            "Section management — student roster, intervention notes, performance dashboards.",
            "One-click quiz generation from the approved question bank, with control over difficulty mix, type mix, and cognitive-bucket mix.",
            "Per-student trend lines and mastery grids.",
        ],
        "short_features": [
            "Dashboard scoped to assigned classes",
            "Browse Learn for assigned subjects",
            "Build quizzes from approved bank",
            "Per-student trends + mastery grid",
        ],
    },
    {
        "key": "student",
        "name": "Student",
        "color": "#22c55e",        # green
        "subtitle": "In-school learner",
        "features": [
            "Take teacher-assigned quizzes; see immediate score and per-question feedback.",
            "Browse chapter content — topic summaries, diagrams, flow charts, 3D scenes.",
            "Personal report card with cognitive-bucket breakdown.",
            "AI tutor chat scoped to a chapter or single topic — refuses off-topic questions, supports 'Easier please' / 'Go deeper' nudges.",
            "Practice quick quizzes between formal assessments.",
        ],
        "short_features": [
            "Take assigned quizzes; see feedback",
            "Browse chapter content + 3D scenes",
            "Report card with cognitive breakdown",
            "AI tutor chat (chapter / topic-scoped)",
        ],
    },
    {
        "key": "individual_learner",
        "name": "Individual learner",
        "color": "#f97316",        # orange
        "subtitle": "Self-paced",
        "features": [
            "Self-signup, no school required — same content catalog as a school student.",
            "Pick any chapter, run a quiz, learn from the topic content.",
            "Personal dashboard, progress tracking, weak topics.",
            "AI tutor chat (premium) for one-on-one help.",
            "Single account per person; platform admin can enable / disable on demand.",
        ],
        "short_features": [
            "Self-signup, no school needed",
            "Quick quiz from any chapter",
            "Personal progress + weak topics",
            "AI tutor chat (premium)",
        ],
    },
]


# Screenshot files the script looks for (relative to docs/marketing/screenshots/).
# Each entry: (filename, caption shown under the image).
# The brochure embeds whichever files exist; missing files are skipped with no
# error. Capture suggestions are documented in
# `docs/marketing/screenshots/README.md`.
ROLE_SCREENSHOTS: dict[str, list[tuple[str, str]]] = {
    "platform_admin": [
        ("01_platform_generate.png",
         "Generate page — pick class, subject, chapter, content type; the LLM uses only the chapter text."),
        ("02_question_bank.png",
         "Question bank — moderate AI-drafted questions before they reach students."),
        ("03_tenants_schools.png",
         "Tenants → Schools — every onboarded school with student / teacher counts."),
        ("04_tenant_school_detail.png",
         "School detail — read-only school admin view with the one-click disable button."),
    ],
    "school_admin": [
        ("05_manage_school_teachers.png",
         "Manage school → Teachers — assign each teacher the subjects they actually teach."),
        ("06_school_report.png",
         "School report — class-wise weak topics, broken down by Factual / Understanding / Application."),
    ],
    "teacher": [
        ("07_teacher_dashboard.png",
         "Teacher dashboard — weak topics card with per-cognitive-level breakdown for the class they teach."),
        ("08_teacher_learn.png",
         "Learn — scoped to assigned subjects only; chapters → topics → practice."),
        ("09_new_quiz.png",
         "New quiz — assemble from approved bank with control over difficulty, type, and cognitive mix."),
    ],
    "student": [
        ("10_take_quiz.png",
         "Taking a quiz — instant per-question feedback after submission."),
        ("11_report_card.png",
         "Report card — overall mastery + per-cognitive-level breakdown."),
        ("12_ai_tutor_chat.png",
         "AI tutor chat — chapter-scoped, refuses off-topic questions, supports difficulty nudges."),
    ],
    "individual_learner": [
        ("13_individual_dashboard.png",
         "Individual learner dashboard — same content as a school student, self-paced."),
        ("14_quick_quiz.png",
         "Quick quiz — pick a chapter, choose a question mix, take it."),
    ],
}

# Cross-cutting screenshots used in the highlight reel.
HIGHLIGHT_SCREENSHOTS: list[tuple[str, str]] = [
    ("15_3d_simulation.png",
     "Generated 3D simulation — rotate, zoom, click any object to learn more."),
    ("16_content_library.png",
     "Content library — every approved artefact, filterable by class, subject, chapter, type."),
    ("17_diagram_svg.png",
     "Generated SVG diagram — concept map that scales cleanly to any projector."),
    ("18_chapter_topics.png",
     "Chapter view — topics list, summary, mind map, flow diagram, simulation, all on one page."),
]


CONTENT_TYPES = [
    ("Worksheet (PDF)",          "Printable practice with mixed question types and an answer key."),
    ("Lesson plan (DOCX)",       "Structured teacher script with objectives, recap, lesson body, activities."),
    ("PPT outline (PPTX)",        "Slide-deck outline a teacher can present or polish further."),
    ("Diagram (SVG)",            "Concept maps and labelled diagrams that scale cleanly to projectors."),
    ("3D Simulation (HTML)",     "Three.js scene with arbitrary 3D layouts — atomic models, food webs, plant anatomy, water cycles."),
    ("Categorize / Match",        "Drag-and-drop and match-the-pairs activities."),
    ("Mind map",                  "Central-term + radiating branches; great for chapter recap."),
    ("Flow diagram",              "Process flow with labelled transitions — water cycle, life cycles, classification trees."),
    ("Chapter summary",           "Bullet-point recap with key terms and 'why it matters'."),
    ("Classroom activity",        "Hands-on group activity with materials and instructions."),
    ("Resource list",             "Curated supplementary reading and external resources."),
]


ANALYTICS = [
    ("Cognitive buckets",
     "Every question is tagged with one of six Bloom levels which roll up to "
     "three coarse buckets: Factual (recall), Understanding (comprehension), "
     "and Application (transfer). Mastery is tracked per (student, outcome, "
     "bucket), so a teacher can see exactly whether the gap is recall, "
     "comprehension, or transfer."),
    ("Class-wise weak topics",
     "For any (class, subject) the platform ranks topics by lowest mastery "
     "across all accessible students, with the per-bucket breakdown surfaced "
     "in line. Available on the teacher Dashboard and the school admin's "
     "School Report."),
    ("Section leaderboards",
     "Per-section ordered list of student averages and mastery, scoped to "
     "subject. Useful for identifying both who needs help and who could lead "
     "peer-tutoring."),
    ("Per-student trend",
     "Time series of evaluated scores by subject — see whether a student is "
     "improving, plateaued, or regressing across assessments."),
    ("Mastery heatmap",
     "Per-student grid of (chapter outcome × cognitive bucket) — instantly "
     "shows which outcomes need work and at which depth."),
]


AI_TUTOR_BULLETS = [
    "Premium per-user feature, off by default — toggled on by the platform team.",
    "Each chat is scoped to either a single chapter or a single topic; the LLM is given just that text and told to refuse off-topic questions.",
    "Optional difficulty nudges: 'Easier please' simplifies; 'Go deeper' surfaces the precise term plus an extra detail.",
    "Conversation persists; the student can return to the same chat later.",
    "Available in English or Hinglish — the tutor matches the student's language.",
]


TENANT_BULLETS = [
    "Every school is a tenant; every individual learner is a 'tenant of one'.",
    "Cross-tenant data is impossible at the API layer — every query is scoped via the JWT's school_id.",
    "Platform admin can disable a school in one click; on the next request, every user in that school is rejected at auth.",
    "Individual learners can be enabled / disabled per user.",
    "Disabling preserves data — re-enable any time and the user picks up exactly where they left off.",
]


TECH_STACK = [
    ("Backend",  "FastAPI + SQLAlchemy 2.0 + Alembic on Python 3.12."),
    ("Database", "PostgreSQL (Supabase). Multi-tenant via row-level school_id scoping."),
    ("Frontend", "React 19 + Vite 8 + TypeScript + Tailwind CSS v4 + TanStack Query."),
    ("LLM",      "Pluggable: Groq (llama-3.3-70b), OpenAI (gpt-4o-mini), Anthropic (claude-sonnet-4-5)."),
    ("Hosting",  "Backend on GCP Cloud Run (scale-to-zero); SPA on Firebase Hosting; artifacts on Cloud Storage."),
    ("Auth",     "JWT (HS256). Per-route role guards. Tenant kill-switch enforced at the auth dependency."),
]


DEMO_SCRIPT = [
    ("1. Sign in as platform admin",
     "Show the curriculum browser (Class 6 Science), then the question bank with draft + approved tabs. Click a draft, approve it, watch the badge change."),
    ("2. Generate content",
     "Open Generate, pick Class 6 -> Science -> Chapter 1, choose '3D Simulation', click Generate. While it runs, narrate that the LLM uses only the chapter text."),
    ("3. Tour the catalog",
     "Open Content library, filter by class + subject + content type, open a worksheet PDF (renders inline) and a 3D simulation (opens in a new tab, interactive)."),
    ("4. Switch to school admin",
     "Open Manage school -> Sections / Teachers / Students. Open Teachers, click Edit subjects on a teacher, assign a subject, save. Open School report — show class roll-up, leaderboards, weak topics by cognitive bucket."),
    ("5. Switch to teacher",
     "Show that the Learn tab and Content library are scoped to assigned subjects only. Open Dashboard — Weak topics card with the Factual / Understanding / Application breakdown."),
    ("6. Switch to student",
     "Take a teacher-assigned quiz. After submission, show the report card. Open AI tutor chat from a topic page — ask a question, then ask an off-topic one and watch it politely refuse."),
    ("7. Tenants surface",
     "Back as platform admin -> Tenants. Show schools list with student/teacher counts, drill into one, demonstrate the Disable school button (with the confirmation card)."),
]


# ---------- PDF generation ---------------------------------------------------


def build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    primary = colors.HexColor(PRIMARY_HEX)
    primary_dark = colors.HexColor(PRIMARY_DARK_HEX)
    muted = colors.HexColor(MUTED_HEX)

    styles: dict[str, ParagraphStyle] = {}
    styles["cover_title"] = ParagraphStyle(
        name="cover_title",
        parent=base["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=40,
        leading=46,
        textColor=primary_dark,
        alignment=TA_LEFT,
        spaceAfter=12,
    )
    styles["cover_tagline"] = ParagraphStyle(
        name="cover_tagline",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=15,
        leading=20,
        textColor=muted,
        alignment=TA_LEFT,
    )
    styles["cover_meta"] = ParagraphStyle(
        name="cover_meta",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=muted,
    )
    styles["section_title"] = ParagraphStyle(
        name="section_title",
        parent=base["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=26,
        textColor=primary_dark,
        spaceAfter=6,
    )
    styles["section_subtitle"] = ParagraphStyle(
        name="section_subtitle",
        parent=base["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=11,
        textColor=muted,
        spaceAfter=10,
    )
    styles["role_chip"] = ParagraphStyle(
        name="role_chip",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=colors.white,
        leading=14,
    )
    styles["body"] = ParagraphStyle(
        name="body",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#0f172a"),
    )
    styles["body_muted"] = ParagraphStyle(
        name="body_muted",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=muted,
    )
    styles["bullet"] = ParagraphStyle(
        name="bullet",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#0f172a"),
        leftIndent=0,
    )
    styles["table_header"] = ParagraphStyle(
        name="table_header",
        parent=base["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=colors.white,
    )
    styles["table_cell"] = ParagraphStyle(
        name="table_cell",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor("#0f172a"),
    )
    styles["table_cell_bold"] = ParagraphStyle(
        name="table_cell_bold",
        parent=styles["table_cell"],
        fontName="Helvetica-Bold",
    )
    styles["page_footer"] = ParagraphStyle(
        name="page_footer",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=8,
        textColor=muted,
        alignment=TA_CENTER,
    )
    return styles


def page_decoration(canvas, doc):
    """Header band + footer with page number on every non-cover page."""
    canvas.saveState()
    page_num = canvas.getPageNumber()
    if page_num == 1:
        canvas.restoreState()
        return
    width, height = A4
    # Slim coloured rule at top
    canvas.setFillColor(colors.HexColor(PRIMARY_HEX))
    canvas.rect(0, height - 0.4 * cm, width, 0.4 * cm, fill=1, stroke=0)
    # Header text
    canvas.setFillColor(colors.HexColor(MUTED_HEX))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(2 * cm, height - 1.0 * cm, "School Tutor — platform overview")
    canvas.drawRightString(width - 2 * cm, height - 1.0 * cm, f"Page {page_num}")
    canvas.restoreState()


def cover_decoration(canvas, doc):
    """Cover page: full-bleed colour band + logo lockup placeholder."""
    canvas.saveState()
    width, height = A4
    canvas.setFillColor(colors.HexColor(PRIMARY_DARK_HEX))
    canvas.rect(0, height - 6 * cm, width, 6 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawString(2 * cm, height - 1.4 * cm, "SCHOOL TUTOR")
    canvas.setFont("Helvetica", 10)
    canvas.drawString(2 * cm, height - 2.0 * cm, "Platform overview & feature catalog")
    canvas.restoreState()


def cover_page(styles: dict[str, ParagraphStyle]) -> list:
    story: list = []
    # Headroom under the coloured band.
    story.append(Spacer(1, 5 * cm))
    story.append(Paragraph("School Tutor", styles["cover_title"]))
    story.append(Paragraph(TAGLINE, styles["cover_tagline"]))
    story.append(Spacer(1, 1.6 * cm))
    story.append(
        Paragraph(
            "A practical walkthrough of every feature, every role, every "
            "content type, and the analytics you can demo to a school or to "
            "a parent.",
            styles["body_muted"],
        )
    )
    story.append(Spacer(1, 0.6 * cm))
    story.append(HRFlowable(width="50%", thickness=1, color=colors.HexColor(PRIMARY_HEX)))
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph(f"Generated {date.today().isoformat()}", styles["cover_meta"]))
    story.append(PageBreak())
    return story


def executive_summary_page(styles: dict[str, ParagraphStyle]) -> list:
    story: list = []
    story.append(Paragraph("Executive summary", styles["section_title"]))
    story.append(
        Paragraph(
            "What School Tutor is, who uses it, and why it matters.",
            styles["section_subtitle"],
        )
    )
    story.append(Paragraph(EXECUTIVE_SUMMARY, styles["body"]))
    story.append(Spacer(1, 0.6 * cm))

    # Embed feature map image right after the summary.
    if PNG_PATH.exists():
        img = Image(str(PNG_PATH))
        # Fit to ~17cm wide, preserve aspect.
        max_w = 17 * cm
        ratio = img.imageHeight / img.imageWidth
        img.drawWidth = max_w
        img.drawHeight = max_w * ratio
        story.append(img)
        story.append(Spacer(1, 0.2 * cm))
        story.append(
            Paragraph(
                "Figure 1. Platform feature map — every role and the capabilities they unlock.",
                styles["body_muted"],
            )
        )
    story.append(PageBreak())
    return story


def _screenshot_flowables(
    filenames_with_captions: list[tuple[str, str]],
    styles: dict[str, ParagraphStyle],
    *,
    max_width: float = 16.5 * cm,
) -> list:
    """Build flowables for each screenshot file that exists on disk.

    Missing files are silently skipped so the brochure still builds when only
    a few screenshots have been captured. Each image is rendered at the given
    max width with aspect preserved, followed by a caption.
    """
    flowables: list = []
    for fname, caption in filenames_with_captions:
        path = SCREENSHOTS_DIR / fname
        if not path.exists():
            continue
        try:
            img = Image(str(path))
            ratio = img.imageHeight / img.imageWidth if img.imageWidth else 1
            img.drawWidth = max_width
            img.drawHeight = max_width * ratio
        except Exception:
            # Don't let a corrupt PNG kill the whole build.
            continue
        block: list = [img, Spacer(1, 0.1 * cm)]
        block.append(Paragraph(f"<i>{caption}</i>", styles["body_muted"]))
        block.append(Spacer(1, 0.5 * cm))
        # KeepTogether so a screenshot doesn't get split across pages.
        flowables.append(KeepTogether(block))
    return flowables


def role_pages(styles: dict[str, ParagraphStyle]) -> list:
    story: list = []
    story.append(Paragraph("Roles & capabilities", styles["section_title"]))
    story.append(
        Paragraph(
            "Five distinct roles, each with a tightly scoped surface. The Tutor "
            "platform never blurs the line between curation, administration, "
            "instruction, and learning.",
            styles["section_subtitle"],
        )
    )
    story.append(Spacer(1, 0.2 * cm))

    for role in ROLES:
        # Coloured chip header.
        chip = Table(
            [[Paragraph(role["name"].upper(), styles["role_chip"])]],
            colWidths=[5.5 * cm],
        )
        chip.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(role["color"])),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ])
        )
        # Header + bullets stay together.
        header_block: list = [chip, Spacer(1, 0.1 * cm)]
        header_block.append(Paragraph(role["subtitle"], styles["body_muted"]))
        header_block.append(Spacer(1, 0.15 * cm))
        items = [
            ListItem(Paragraph(f, styles["bullet"]), leftIndent=10, value=None)
            for f in role["features"]
        ]
        header_block.append(
            ListFlowable(
                items, bulletType="bullet", start="•",
                leftIndent=14, bulletFontName="Helvetica-Bold",
            )
        )
        header_block.append(Spacer(1, 0.4 * cm))
        story.append(KeepTogether(header_block))

        # Screenshots specific to this role, embedded one per row underneath
        # the bullets. Skipped silently if the PNG isn't present.
        screenshots = ROLE_SCREENSHOTS.get(role["key"], [])
        story.extend(_screenshot_flowables(screenshots, styles))

        story.append(PageBreak())
    return story


def highlights_page(styles: dict[str, ParagraphStyle]) -> list:
    """A 'highlight reel' section with the cross-cutting screenshots.

    Skipped entirely if no highlight screenshots have been captured yet.
    """
    flowables = _screenshot_flowables(HIGHLIGHT_SCREENSHOTS, styles)
    if not flowables:
        return []

    story: list = []
    story.append(Paragraph("Highlights", styles["section_title"]))
    story.append(
        Paragraph(
            "A few standout surfaces that don't fit neatly into one role.",
            styles["section_subtitle"],
        )
    )
    story.extend(flowables)
    story.append(PageBreak())
    return story


def content_catalog_page(styles: dict[str, ParagraphStyle]) -> list:
    story: list = []
    story.append(Paragraph("Content catalog", styles["section_title"]))
    story.append(
        Paragraph(
            "Every artefact is generated by an LLM against the actual chapter "
            "text, then reviewed and approved by the platform team before it "
            "reaches a school.",
            styles["section_subtitle"],
        )
    )

    rows = [[Paragraph("Type", styles["table_header"]),
             Paragraph("What it is", styles["table_header"])]]
    for name, desc in CONTENT_TYPES:
        rows.append([
            Paragraph(name, styles["table_cell_bold"]),
            Paragraph(desc, styles["table_cell"]),
        ])
    table = Table(rows, colWidths=[5.0 * cm, 11.5 * cm], repeatRows=1)
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(PRIMARY_DARK_HEX)),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.white, colors.HexColor(CARD_BG_HEX)]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LINEBELOW", (0, 0), (-1, 0), 1, colors.HexColor(PRIMARY_HEX)),
        ])
    )
    story.append(table)
    story.append(PageBreak())
    return story


def analytics_page(styles: dict[str, ParagraphStyle]) -> list:
    story: list = []
    story.append(Paragraph("Analytics & insights", styles["section_title"]))
    story.append(
        Paragraph(
            "Every evaluated submission updates a per-student mastery model. "
            "The dashboards roll those up for the audience that needs them.",
            styles["section_subtitle"],
        )
    )

    for name, desc in ANALYTICS:
        block: list = []
        block.append(Paragraph(f"<b>{name}</b>", styles["body"]))
        block.append(Paragraph(desc, styles["body_muted"]))
        block.append(Spacer(1, 0.4 * cm))
        story.append(KeepTogether(block))

    story.append(PageBreak())
    return story


def ai_tutor_page(styles: dict[str, ParagraphStyle]) -> list:
    story: list = []
    story.append(Paragraph("AI tutor (premium)", styles["section_title"]))
    story.append(
        Paragraph(
            "Personal one-on-one help, but rigorously scoped so the model "
            "stays on the chapter.",
            styles["section_subtitle"],
        )
    )
    items = [
        ListItem(Paragraph(b, styles["bullet"]), leftIndent=10)
        for b in AI_TUTOR_BULLETS
    ]
    story.append(
        ListFlowable(items, bulletType="bullet", start="•", leftIndent=14)
    )
    story.append(PageBreak())
    return story


def tenants_page(styles: dict[str, ParagraphStyle]) -> list:
    story: list = []
    story.append(Paragraph("Multi-tenancy & access control", styles["section_title"]))
    story.append(
        Paragraph(
            "Every school, every individual, isolated. Platform-admin "
            "controls let you onboard, monitor, and revoke access without "
            "touching code.",
            styles["section_subtitle"],
        )
    )
    items = [
        ListItem(Paragraph(b, styles["bullet"]), leftIndent=10)
        for b in TENANT_BULLETS
    ]
    story.append(
        ListFlowable(items, bulletType="bullet", start="•", leftIndent=14)
    )
    story.append(PageBreak())
    return story


def tech_stack_page(styles: dict[str, ParagraphStyle]) -> list:
    story: list = []
    story.append(Paragraph("Under the hood", styles["section_title"]))
    story.append(
        Paragraph(
            "Conventional, boring choices. Easy to hand off, easy to scale.",
            styles["section_subtitle"],
        )
    )
    rows = [[Paragraph("Layer", styles["table_header"]),
             Paragraph("Implementation", styles["table_header"])]]
    for name, desc in TECH_STACK:
        rows.append([
            Paragraph(name, styles["table_cell_bold"]),
            Paragraph(desc, styles["table_cell"]),
        ])
    table = Table(rows, colWidths=[3.5 * cm, 13.0 * cm], repeatRows=1)
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(PRIMARY_DARK_HEX)),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.white, colors.HexColor(CARD_BG_HEX)]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ])
    )
    story.append(table)
    story.append(PageBreak())
    return story


def demo_script_page(styles: dict[str, ParagraphStyle]) -> list:
    story: list = []
    story.append(Paragraph("Suggested demo flow", styles["section_title"]))
    story.append(
        Paragraph(
            "A 7-step walkthrough that hits every major surface in roughly "
            "12 minutes. Use as a script or freestyle.",
            styles["section_subtitle"],
        )
    )

    for title, body in DEMO_SCRIPT:
        block: list = []
        block.append(Paragraph(f"<b>{title}</b>", styles["body"]))
        block.append(Paragraph(body, styles["body_muted"]))
        block.append(Spacer(1, 0.35 * cm))
        story.append(KeepTogether(block))

    return story


def build_pdf(out_path: Path) -> None:
    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title="School Tutor — Platform overview",
        author="School Tutor platform team",
    )
    styles = build_styles()

    story: list = []
    story.extend(cover_page(styles))
    story.extend(executive_summary_page(styles))
    story.extend(role_pages(styles))
    story.extend(highlights_page(styles))
    story.extend(content_catalog_page(styles))
    story.extend(analytics_page(styles))
    story.extend(ai_tutor_page(styles))
    story.extend(tenants_page(styles))
    story.extend(tech_stack_page(styles))
    story.extend(demo_script_page(styles))

    # Different page deco for cover (page 1) vs. interior pages.
    doc.build(
        story,
        onFirstPage=cover_decoration,
        onLaterPages=page_decoration,
    )


# ---------- Image generation -------------------------------------------------


def build_feature_map(out_path: Path) -> None:
    """One landscape PNG with all five roles, content types, and analytics."""
    fig = plt.figure(figsize=(16, 9), facecolor="white")
    ax = fig.add_axes([0, 0, 1, 1])
    ax.set_xlim(0, 16)
    ax.set_ylim(0, 9)
    ax.axis("off")

    # Top banner
    banner = mpatches.FancyBboxPatch(
        (0, 8.0), 16, 1.0,
        boxstyle="square,pad=0",
        facecolor=PRIMARY_DARK_HEX, edgecolor="none",
    )
    ax.add_patch(banner)
    ax.text(0.5, 8.62, "SCHOOL TUTOR",
            color="white", fontsize=22, fontweight="bold", va="center")
    ax.text(0.5, 8.22, TAGLINE,
            color="#cbd5e1", fontsize=12, va="center")
    ax.text(15.5, 8.45, "Platform feature map",
            color="white", fontsize=11, va="center", ha="right",
            fontstyle="italic")

    # Five role cards across.
    n = len(ROLES)
    margin_x = 0.4
    gap = 0.18
    total_w = 16 - 2 * margin_x - (n - 1) * gap
    card_w = total_w / n
    card_top = 7.6
    card_bottom = 3.7
    card_h = card_top - card_bottom

    for i, role in enumerate(ROLES):
        x = margin_x + i * (card_w + gap)
        # Card background
        card = mpatches.FancyBboxPatch(
            (x, card_bottom), card_w, card_h,
            boxstyle="round,pad=0.02,rounding_size=0.18",
            facecolor=CARD_BG_HEX, edgecolor="#cbd5e1", linewidth=1,
        )
        ax.add_patch(card)
        # Coloured header strip at the top of the card
        head = mpatches.FancyBboxPatch(
            (x, card_top - 0.7), card_w, 0.7,
            boxstyle="round,pad=0.02,rounding_size=0.18",
            facecolor=role["color"], edgecolor="none",
        )
        ax.add_patch(head)
        # Cover the rounded bottom of the head with a flat strip so it
        # blends into the card body.
        ax.add_patch(
            mpatches.Rectangle(
                (x + 0.05, card_top - 0.7),
                card_w - 0.10, 0.18,
                facecolor=role["color"], edgecolor="none",
            )
        )
        ax.text(x + card_w / 2, card_top - 0.32,
                role["name"],
                color="white", fontsize=12, fontweight="bold",
                ha="center", va="center")
        ax.text(x + card_w / 2, card_top - 0.55,
                role["subtitle"],
                color="white", fontsize=8.5, alpha=0.85,
                ha="center", va="center", fontstyle="italic")

        # Bullet list. matplotlib's `ax.text` doesn't wrap by default, so we
        # split each bullet into multiple lines manually with textwrap and
        # render line-by-line at the right line spacing.
        bullets = role["short_features"][:4]
        wrap_width = 26                 # characters per line, ~card_w wide
        line_height = 0.21              # axis units per text line
        bullet_gap = 0.16               # extra space between bullets
        cursor_y = card_top - 1.0
        for b in bullets:
            wrapped = textwrap.wrap(b, width=wrap_width) or [""]
            # Bullet glyph aligned with the first line.
            ax.text(x + 0.20, cursor_y, "•",
                    fontsize=11, color=role["color"],
                    fontweight="bold", va="top")
            for i, line in enumerate(wrapped):
                ax.text(x + 0.45, cursor_y - i * line_height, line,
                        fontsize=9, color="#0f172a", va="top")
            cursor_y -= line_height * len(wrapped) + bullet_gap

    # Bottom band: content types + analytics callouts
    band_top = 3.4
    band_h = 2.7
    # Left card: content
    cl = mpatches.FancyBboxPatch(
        (0.4, band_top - band_h), 7.6, band_h,
        boxstyle="round,pad=0.02,rounding_size=0.18",
        facecolor=SOFT_BG_HEX, edgecolor="#c7d2fe", linewidth=1,
    )
    ax.add_patch(cl)
    ax.text(0.7, band_top - 0.35, "Content catalog",
            fontsize=13, fontweight="bold", color=PRIMARY_DARK_HEX, va="center")
    ax.text(0.7, band_top - 0.75,
            "AI-generated, human-curated, served to every classroom",
            fontsize=9, color=MUTED_HEX, va="center", fontstyle="italic")
    # Render content types as a wrapped block of " · " separated names so
    # nothing spills off the card.
    content_names = [c[0] for c in CONTENT_TYPES]
    catalog_text = " · ".join(content_names)
    catalog_lines = textwrap.wrap(catalog_text, width=68)
    cy = band_top - 1.20
    for line in catalog_lines[:3]:
        ax.text(0.7, cy, line,
                fontsize=9.5, color="#0f172a", va="center")
        cy -= 0.32
    ax.text(0.7, cy - 0.10,
            "PDFs render inline · simulations open as interactive 3D · diagrams scale as SVG.",
            fontsize=9, color=MUTED_HEX, va="center", fontstyle="italic")

    # Right card: analytics + AI tutor
    cr = mpatches.FancyBboxPatch(
        (8.2, band_top - band_h), 7.4, band_h,
        boxstyle="round,pad=0.02,rounding_size=0.18",
        facecolor="#ecfdf5", edgecolor="#bbf7d0", linewidth=1,
    )
    ax.add_patch(cr)
    ax.text(8.5, band_top - 0.35, "Analytics & AI tutor",
            fontsize=13, fontweight="bold",
            color="#065f46", va="center")
    ax.text(8.5, band_top - 0.75,
            "Insight that makes the catalog actionable",
            fontsize=9, color=MUTED_HEX, va="center", fontstyle="italic")
    analytics_chips = [
        ("Cognitive buckets", "Factual · Understanding · Application"),
        ("Weak topics",        "Class-wise · per-bucket breakdown"),
        ("Trends",             "Per-student over time"),
        ("AI tutor",           "Chapter / topic-scoped, refuses off-topic"),
    ]
    line_y = band_top - 1.20
    for label, body in analytics_chips:
        ax.text(8.5, line_y,
                f"• {label}: ",
                fontsize=10, color="#065f46",
                fontweight="bold", va="top")
        ax.text(11.2, line_y, body,
                fontsize=10, color="#0f172a", va="top")
        line_y -= 0.40

    # Footer
    ax.text(0.4, 0.4,
            "School Tutor · CBSE/NCERT-aligned · "
            "Multi-tenant: each school is isolated, individual learners are tenants of one.",
            fontsize=9, color=MUTED_HEX, va="center")
    ax.text(15.6, 0.4,
            f"Generated {date.today().isoformat()}",
            fontsize=8.5, color=MUTED_HEX, va="center", ha="right",
            fontstyle="italic")

    fig.savefig(out_path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)


# ---------- Driver -----------------------------------------------------------


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Writing feature map -> {PNG_PATH.relative_to(REPO_ROOT)}")
    build_feature_map(PNG_PATH)
    print(f"Writing brochure   -> {PDF_PATH.relative_to(REPO_ROOT)}")
    build_pdf(PDF_PATH)
    print("Done.")


if __name__ == "__main__":
    main()
