"""Second batch of supplementary questions for Class 10 Social Science Ch1 chapters.
Targets gaps: Civics + Economics objective; subjective across all four.
"""

from sqlalchemy import select
from app.db.session import SessionLocal
from app.models.curriculum import BloomLevel, LearningOutcome
from app.models.question import Question, QuestionDifficulty, QuestionStatus, QuestionType

CREATED_BY_ID = 14


def _options(q):
    return {"choices": list(q["options"])} if q.get("options") else None


def insert_for_chapter(db, chapter_id, supp):
    outcome_map = {r.code: r.id for r in db.scalars(
        select(LearningOutcome).where(LearningOutcome.chapter_id == chapter_id)).all()}
    existing = {r.text for r in db.scalars(
        select(Question).where(Question.chapter_id == chapter_id)).all()}
    added = 0
    for q in supp:
        if q["question"] in existing: continue
        oc = q.get("outcome_code")
        db.add(Question(
            chapter_id=chapter_id, topic_id=None,
            outcome_id=outcome_map.get(oc) if oc else None, outcome_code=oc,
            type=QuestionType(q["type"]), difficulty=QuestionDifficulty(q["difficulty"]),
            status=QuestionStatus.APPROVED,
            cognitive_level=BloomLevel(q["cognitive_level"].lower()),
            text=q["question"], options=_options(q), correct_answer=q["answer"],
            explanation=q.get("explanation"), marks=int(q.get("marks", 1)),
            created_by_id=CREATED_BY_ID))
        added += 1
    db.commit()
    return added


# History — needs ~10 more subjective
EXTRA_197 = [
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-01","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"Who was Frédéric Sorrieu and what were his 1848 prints?","answer":"Frédéric Sorrieu (1807-87) was a French painter who in 1848 prepared a series of FOUR PRINTS visualising his dream of a world made up of 'democratic and social Republics'. The prints showed peoples of Europe and America — men and women of all classes — paying homage to a giant statue of Liberty. They captured the political imagination of nineteenth-century European nationalism: a world of free, self-governing nations united in fraternity.","explanation":"Sorrieu and his prints."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-03","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"What was the Confederation of the Rhine? When was it organised?","answer":"The Confederation of the Rhine was a league of GERMAN STATES created by Napoleon in 1806 after he defeated Austria. It abolished the Holy Roman Empire and consolidated 39 small kingdoms, duchies and principalities into a much smaller number of administratively rationalised states. Within these states Napoleon imposed his Civil Code, abolished feudalism and reformed administration. After Napoleon's fall the Confederation was dissolved at the Congress of Vienna (1815), but its administrative reforms left a lasting impact on the path to German unification.","explanation":"Confederation of the Rhine."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-04","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"Who were the Junkers? What role did they play in German nationalism?","answer":"The JUNKERS were the large, conservative, land-owning aristocracy of PRUSSIA — east of the Elbe river. They dominated the Prussian army officer corps and, alongside the King and Bismarck, formed the social backbone of CONSERVATIVE NATIONALISM in Germany. They supported Bismarck's wars of unification (1864/1866/1870-71) and the establishment of the German Empire in 1871. Without their support neither the Prussian army nor the new Empire could have been built. They were thus a key — though deeply conservative — driving force of German national consolidation.","explanation":"Junkers and German nationalism."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-05","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"What happened to nationalism in Hungary in 1848?","answer":"In 1848 Hungarians, led by Lajos KOSSUTH, demanded autonomy from the Habsburg Empire and even declared a Hungarian Republic in 1849. The movement was inspired by liberal-nationalist ideals — a Hungarian parliament, Hungarian language, equal civil rights. The Habsburg emperor, with the help of Russian troops, ultimately suppressed the Hungarian revolt by 1849. But the Hungarian challenge forced the Habsburg crown into a series of compromises that culminated in the AUSTRO-HUNGARIAN COMPROMISE of 1867 — granting Hungary effective autonomy as the second half of a 'dual monarchy'. Hungary's 1848 thus failed in the short run but reshaped the empire in the long run.","explanation":"Hungarian 1848."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-06","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"What was the Zollverein? How did it help German unification?","answer":"The ZOLLVEREIN — German for 'customs union' — was a customs union among most German states created in 1834 under Prussian leadership. It abolished tariff barriers between member states and allowed free movement of goods. Two effects on unification: (i) ECONOMIC INTEGRATION made German states inter-dependent; cargo, businessmen and workers moved freely, weakening political fragmentation. (ii) Prussia, the largest economic power, became the natural leader of the union — laying the ground for its political leadership later under Bismarck. The Zollverein was thus a quiet but decisive step toward 1871.","explanation":"Zollverein → German unity."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-06","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"How did Garibaldi's march to the south of Italy succeed?","answer":"In May 1860, Giuseppe GARIBALDI sailed from Genoa with about a thousand red-shirted volunteers ('I MILLE') and landed in SICILY. He defeated the Bourbon armies in a series of battles, gathered local peasants disillusioned with the Bourbon kings, and crossed to the mainland. By September 1860 he marched into NAPLES, ending Bourbon rule in southern Italy. Rather than declaring his own kingdom, he handed the conquered territories to King Victor Emmanuel II of Sardinia-Piedmont — the act that made the unification of Italy possible. In March 1861, Victor Emmanuel II was proclaimed KING OF UNITED ITALY.","explanation":"Garibaldi's southern campaign."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-08","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"How was Britannia different from Marianne and Germania, and why?","answer":"BRITANNIA, the female allegory of Britain, was a settled imperial figure: usually crowned, holding a trident and shield, sitting calmly on a rock. She represented an ESTABLISHED, IMPERIAL nation — the world's leading naval and economic power — not a nation struggling to emerge. MARIANNE (France) and GERMANIA (Germany), by contrast, were YOUNG REVOLUTIONARY allegories of nations BEING BORN — Marianne with the red cap of liberty waving the tricolour, Germania with the German sword in hand. The visual difference reflects the historical situation: Britain in the 19th century was ALREADY a unified nation-state, while France and Germany were still working out what their nations should be.","explanation":"Britannia vs Marianne / Germania."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-04","difficulty":"HARD","cognitive_level":"ANALYZE","marks":5,"question":"How did the Romantic movement contribute to nationalist sentiment in 19th-century Europe?","answer":"ROMANTICISM was a cultural and intellectual movement that emerged in the late 18th century and dominated much of the 19th. It REJECTED the Enlightenment's emphasis on cold reason and celebrated EMOTIONS, INTUITION, MYSTICAL FEELINGS, FOLK CULTURE and the SPIRITUAL DIMENSION of human life. Several ways it contributed to nationalism: (i) IT REDEFINED THE NATION — not as a political contract among individuals, but as a SPIRITUAL COMMUNITY (das Volk) sharing language, history, songs and traditions. Johann Gottfried Herder argued that the true 'spirit of the people' was found in folk songs, fairy tales and dances. (ii) IT REVIVED VERNACULAR LANGUAGES AND FOLK CULTURE — the Grimm brothers in Germany collected fairy tales; Polish musicians composed national operas; Italian writers revived their language. (iii) IT GAVE NATIONALISM EMOTIONAL POWER — paintings, music, poetry, novels and plays portrayed national heroes, defeats and dreams in a way that moved ordinary people to action. Beethoven dedicated his Third Symphony to revolutionary France; Verdi's operas became symbols of Italian unification. (iv) IT LINKED LANGUAGE WITH POLITICAL FREEDOM — in partitioned Poland, the use of the Polish language in church services and operas was a form of national resistance. Together with the political programme of the educated middle class (liberty, constitution, equality), the cultural programme of the Romantics gave 19th-century European nationalism BOTH its political demands AND its emotional motive force.","explanation":"Romanticism + nationalism."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-07","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"Discuss the formation of the British nation-state. Why is it considered different from the French model?","answer":"Britain's nation-state did NOT emerge from a single revolution. Instead it was the result of a LONG-DRAWN PROCESS in which the English nation steadily extended its dominance over the British Isles. Key milestones: (i) Before the 18th century, the inhabitants of the British Isles had ETHNIC IDENTITIES — English, Welsh, Scot, Irish — not a 'British' identity. (ii) The English parliament, having seized power from the monarchy in 1688 (Glorious Revolution), became the instrument through which a nation-state was built. (iii) ACT OF UNION 1707 between England and Scotland created the 'United Kingdom of Great Britain' — the parliament was henceforth dominated by English members; Scotland's older institutions survived only as junior partners. (iv) IRELAND was forcibly incorporated in 1801. (v) Symbols of the new Britain — the UNION JACK, the national anthem ('God Save Our Noble King'), the English language — were actively PROMOTED, while older Welsh, Scot and Irish identities survived only as subordinate partners. WHY DIFFERENT FROM FRANCE? FRANCE became a nation through SUDDEN REVOLUTION (1789) that overthrew the king and proclaimed sovereignty of the people; the new community of citizens was forged through new institutions, a new flag and a new common language. BRITAIN became a nation through SLOW, ENGLISH-LED INCORPORATION OF ITS ISLAND NEIGHBOURS — through Acts of Union, parliamentary politics and the projection of an English-led 'British' culture. France's nation was built by revolution; Britain's nation was assembled by political and cultural dominance over time.","explanation":"British vs French nation-formation."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-HIS-RNE-08","difficulty":"HARD","cognitive_level":"ANALYZE","marks":5,"question":"How did female allegories help in transforming nations into 'beings' that citizens could love and serve?","answer":"In the 19th century, ARTISTS, POETS and SCULPTORS PERSONIFIED nations as FEMALE FIGURES — known as ALLEGORIES. Each had specific symbols: MARIANNE, with the red cap of liberty (Phrygian cap), the tricolour and the cockade, embodied LIBERTY and the FRENCH REPUBLIC; her statues stood in public squares and her image appeared on coins and stamps. GERMANIA, with a CROWN OF OAK LEAVES (the German oak symbolised heroism), embodied GERMAN national strength and unity. BRITANNIA, with trident and shield, embodied a settled imperial Britain. Why FEMALE figures? They linked the nation with values considered desirable in 19th-century Europe — beauty, motherhood, courage in defence of children, moral purity, and capacity to evoke love. Several effects: (i) the nation became a BEING that citizens could love — like a mother — not just an abstract idea. (ii) Patriotism became EMOTIONALLY POWERFUL — soldiers fought for 'la patrie', for 'die Mutter Heimat'. (iii) Public spaces (squares, monuments, school halls) became filled with these symbols — making nationalism visible in everyday life. (iv) Currency, stamps and official documents carried these images — reinforcing national identity in mundane transactions. (v) Women were paradoxically EXCLUDED from political rights even as they were embraced as symbols of the nation; the fight for women's suffrage was a long parallel struggle in the 19th and 20th centuries. The female allegory was thus a powerful tool of nation-building — but it also reflected the contradictions of an age that loved 'Mother Nation' while denying daughters and wives the vote.","explanation":"Female allegory function in detail."},
]

# Geography — needs ~12 more subjective
EXTRA_202 = [
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-01","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"Explain why even the same physical thing can be a resource in one place and not in another, with two examples.","answer":"Because resources are products of NATURE × TECHNOLOGY × INSTITUTIONS, the same physical thing can be a resource in one society and not in another. EXAMPLE 1 — DEEP-SEA OIL is a major resource for countries like Norway and Saudi Arabia, which have the technology and capital to drill; for a poor nation without that capacity, the oil is just rock-bound stock. EXAMPLE 2 — PINE FORESTS are revered as sacred groves in some adivasi areas of India and protected from cutting; in another society the same forest is a timber resource. EXAMPLE 3 — NATURAL GAS reserves became 'resources' for many countries only after fracking technology emerged in the 2000s. So the very status of a thing as a 'resource' depends on technology, economics and culture.","explanation":"Resource = social construction."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-03","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"What were the three main outcomes of the Rio Earth Summit (1992)?","answer":"More than 100 heads of state met in Rio de Janeiro in June 1992 to address environmental and development concerns. Three major outcomes: (i) DECLARATION ON CLIMATE CHANGE — laying foundations for the later Kyoto and Paris agreements. (ii) CONVENTION ON BIOLOGICAL DIVERSITY (CBD) — to conserve biological diversity, ensure sustainable use and equitable benefit-sharing. (iii) AGENDA 21 — a global plan of action for sustainable development; every local government to draw its own LOCAL AGENDA 21. The Summit signalled a global commitment to combine economic development with environmental protection.","explanation":"Three outcomes of Rio."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-04","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"Why is mineral wealth alone not enough for the prosperity of a state? Cite Indian examples.","answer":"States like Jharkhand, Chhattisgarh, Odisha and parts of Madhya Pradesh are RICH in coal, iron ore, bauxite and other minerals. Yet many of their districts have HIGH POVERTY rates. Mineral wealth without good resource planning can lead to: (i) ENVIRONMENTAL DEGRADATION — mining without restoration; deforestation; water pollution. (ii) WEAK LOCAL BENEFITS — minerals are extracted and exported elsewhere; royalties and jobs do not always reach local people. (iii) DISPLACEMENT of local communities (often adivasi) without proper rehabilitation. (iv) NEGLECT of agriculture, education and health. So a state must have not only resources but also INSTITUTIONS for fair distribution, environmental protection and skill development. Resource planning + Local Agenda 21 are designed to address this.","explanation":"Resource curse + planning."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-05","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"Why is land considered the most basic resource for human civilisation?","answer":"Land is the BASIS for almost all human activity. (i) AGRICULTURE — about 60% of Indians depend on land for food and livelihood. (ii) HOUSING and INFRASTRUCTURE — every house, road, school, factory needs land. (iii) NATURAL VEGETATION and WILDLIFE depend on land. (iv) Land supports ECONOMIC activities including industry, mining and tourism, and is the medium for TRANSPORT and COMMUNICATION. (v) Land carries the MINERAL WEALTH below it. (vi) Land has CULTURAL and SPIRITUAL value for communities — adivasi tribes call themselves children of the soil. Without land, none of the higher economic activities is possible. Yet land is FINITE — therefore careful planning of its use is one of the most important issues in any country.","explanation":"Land as basic resource."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-06","difficulty":"MEDIUM","cognitive_level":"APPLY","marks":3,"question":"Suggest five ways to combat land degradation in mining-affected regions.","answer":"(i) FILL AND RESTORE the open mining pits after extraction is complete; convert them into ponds or plantations. (ii) AFFORESTATION on mined hills — planting native species suited to the soil and climate. (iii) Treat and DISPOSE INDUSTRIAL EFFLUENTS properly so they do not pollute land or water. (iv) STRICT REGULATION of mining licences; mining only after environmental impact assessment; involve local communities. (v) BIOLOGICAL RECLAMATION — using grasses and shrubs that improve soil quality. (vi) Restoration of FOREST cover and protection of wildlife corridors. (vii) JOINT FOREST MANAGEMENT with adivasi communities under the Forest Rights Act. Together, these steps can restore degraded mined land over time.","explanation":"Five+ remedies."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-07","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"What is the difference between Khadar and Bangar alluvial soils?","answer":"Both are types of ALLUVIAL soil found in the northern plains of India, but: KHADAR is the YOUNGER alluvium, deposited by river floods every year. It has finer particles, more humus and is more FERTILE. It is the soil of the Bhabar / Tarai and floodplains. BANGAR is the OLDER alluvium, lying away from active flood-plains. It is older, slightly coarser, has more KANKAR (lime nodules) in the lower horizons and is somewhat less fertile than Khadar. Khadar is renewed every year while Bangar is essentially fixed.","explanation":"Khadar vs Bangar."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-07","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"Why does black soil develop deep cracks during the hot weather, and how is this useful?","answer":"Black soils contain a high proportion of CLAY (extremely fine particles) which holds water. During the cold and wet seasons the soil is moist and SWELLS. In the HOT, DRY months, water EVAPORATES from the soil and the clay particles SHRINK, opening up DEEP CRACKS on the surface. These cracks are useful in two ways: (i) they help in PROPER AERATION of the soil — air reaches deep layers, important for root and microbial activity. (ii) When the next rains come, water soaks deep into the cracks, recharging the soil profile. Farmers traditionally TILL black soil immediately after the first showers — when it is still soft but not yet sticky.","explanation":"Black soil cracks."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-07","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"Why are arid soils naturally low in humus? How can they still be made productive?","answer":"In arid regions of western Rajasthan and adjacent areas, low rainfall and very high day-time temperatures result in: (i) SCANT vegetation and therefore LITTLE organic matter falling to the ground; (ii) HIGH evaporation that quickly removes any moisture; (iii) high temperatures that destroy soil micro-organisms; (iv) lower-soil layers full of KANKAR (lime nodules) that block water infiltration. As a result, humus is naturally low. With careful management, however, these soils can be made productive: PROPER IRRIGATION (with the Indira Gandhi Canal in western Rajasthan, large areas have been brought under cultivation), addition of MANURES and ORGANIC MATTER, growing of DROUGHT-RESISTANT crops like millets and gram, and SOIL CONSERVATION measures like shelter belts.","explanation":"Why low humus + remedies."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-08","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"What is wind erosion? In which Indian regions is it most severe?","answer":"WIND EROSION is the removal of loose, dry topsoil from flat or gently sloping land by strong WINDS. It is most severe in REGIONS WITH LOW VEGETATION and SANDY soils — chiefly the Thar desert and adjacent western Rajasthan, the Rann of Kutch in Gujarat, and parts of the Punjab plains. Causes include over-grazing, deforestation and dry-fallow cultivation. Effects: loss of fertile topsoil, encroachment of sand dunes onto fields, and reduction in agricultural productivity. Conservation: planting SHELTER BELTS (rows of trees along field edges), stabilising sand dunes with thorny bushes, and reviving vegetation cover have helped significantly in western Rajasthan.","explanation":"Wind erosion + Indian regions."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-04","difficulty":"HARD","cognitive_level":"APPLY","marks":5,"question":"You are asked to plan resource use for a coastal Indian state. Suggest a five-point plan that balances development with sustainability.","answer":"For a coastal Indian state — say Kerala or Gujarat — I would propose: (1) MAP RESOURCES carefully — coastal land use, fisheries, tourism potential, mineral sands, fresh-water aquifers, mangroves and biodiversity hotspots. Make a detailed inventory. (2) PROTECT MANGROVES AND COASTAL ECOSYSTEMS that prevent erosion, host fisheries and absorb carbon. Stop further encroachment by industry and aquaculture. (3) SUSTAINABLE FISHERIES — enforce closed-season rules, regulate trawler size, ban destructive trawling near reefs; support traditional fisher livelihoods with insurance, cold storage and minimum-price arrangements. (4) MIXED INDUSTRY-AGRICULTURE-TOURISM ECONOMY — diversify so the state does not depend on any one resource; promote eco-tourism, organic spice farming, fisheries-based food industry, IT and skill-based service sectors. (5) RAINWATER HARVESTING + WATER MANAGEMENT — store monsoon water in tanks; recharge aquifers; control over-pumping that causes saline-water intrusion. (6) DISASTER PREPAREDNESS — early-warning systems for cyclones, mangrove buffer zones, climate-resilient coastal infrastructure. (7) JOINT-MANAGEMENT institutions with PANCHAYATS — ensure fishermen, farmers and women are part of decision-making. The plan balances DEVELOPMENT (jobs, income, infrastructure) with SUSTAINABILITY (ecosystems, water, climate resilience), drawing on the Resource Planning framework, Agenda 21 and Indian state experience.","explanation":"Coastal state plan."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-07","difficulty":"HARD","cognitive_level":"ANALYZE","marks":5,"question":"Explain how parent rock, climate, vegetation and time interact to form different soil types in India.","answer":"Soil takes MILLIONS of years to form even a few centimetres of depth. Five factors interact in its formation: PARENT ROCK supplies the mineral content. CLIMATE controls weathering, leaching, water retention and microbial activity. RELIEF determines drainage and erosion. VEGETATION supplies humus and protects from erosion. TIME allows the soil profile to develop. Examples in India: (i) ALLUVIAL — the parent material is sediment carried by Himalayan and peninsular RIVERS over time; the gentle slope of the plains traps these sediments; the moderate climate aids fertility. (ii) BLACK / REGUR — parent material is BASALT (volcanic lava); the dry-and-wet climate of the Deccan plateau allows clay-mineral formation; intense weathering produces a clayey, moisture-holding soil rich in calcium, potash, lime. (iii) RED & YELLOW — parent rock is CRYSTALLINE IGNEOUS ROCK; low rainfall keeps the soil in place; iron oxide gives the red colour. (iv) LATERITE — parent rocks of the Western Ghats and Eastern Ghats; under HIGH RAIN + HEAT, intense leaching washes away lime and silica leaving a residual iron-and-aluminium soil. (v) ARID — parent rock plus dry climate plus minimal vegetation produce sandy, saline soils with kankar layers. (vi) FOREST — hilly slopes plus wet climate plus thick vegetation produce loamy, humus-rich (in lower areas) and acidic (on high slopes) soils. So India's wide variety of soils mirrors its variety of parent rocks, climates, slopes and vegetation — a geographical mosaic.","explanation":"Soil formation factors."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-GEO-RD-08","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"Why is soil conservation critical for India's future? Discuss with three regional examples.","answer":"India loses MILLIONS of tonnes of topsoil every year to erosion and degradation — and topsoil takes centuries to form. Soil conservation is therefore CRITICAL for: (i) FOOD SECURITY of 1.4 billion people; (ii) RURAL LIVELIHOODS that depend on agriculture and animal husbandry; (iii) WATER security (degraded land cannot retain water); (iv) BIODIVERSITY conservation; (v) CLIMATE RESILIENCE (healthy soils store carbon). REGIONAL EXAMPLES: (a) THE HIMALAYAS — steep slopes, heavy monsoon rain, deforestation and over-grazing have caused severe erosion; remedy = TERRACE cultivation and afforestation that have helped in Himachal Pradesh and Uttarakhand. (b) THE CHAMBAL BASIN (MP, Rajasthan, UP) — gully erosion has created vast 'bad lands' / RAVINES; remedy = check dams, contour bunds, shelter belts, and reclamation projects. (c) WESTERN RAJASTHAN — wind erosion, sand-dune migration; remedy = SHELTER BELTS of trees, stabilisation of dunes with thorny bushes; the Indira Gandhi Canal has also brought irrigation. (d) PUNJAB / HARYANA — over-irrigation has caused water-logging and salinity; remedy = drip irrigation, salt-tolerant crops, drainage. Each region needs its own conservation mix. Without a nationwide effort, India risks losing fertility, biodiversity and water — the very resources future generations will need most.","explanation":"Soil conservation national + regional."},
]

# Civics — needs ~16 obj + ~14 subj
EXTRA_209 = [
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"Which language is spoken by 1% of Belgians?","options":["Dutch","French","German","English"],"answer":"German","explanation":"Small German-speaking minority."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"Wallonia is the southern region of Belgium where people speak:","options":["Dutch","French","German","Spanish"],"answer":"French","explanation":"Walloon = French."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-01","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"What was the SOURCE of the tension between Dutch and French speakers in mid-20th century Belgium?","options":["religious","class + language overlap (richer minority French-speakers)","weather","Belgium's small size"],"answer":"class + language overlap (richer minority French-speakers)","explanation":"Class-language overlap."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-02","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"What is the capital of Sri Lanka?","options":["Jaffna","Kandy","Colombo (commercial)/Sri Jayawardenepura Kotte (legislative)","Trincomalee"],"answer":"Colombo (commercial)/Sri Jayawardenepura Kotte (legislative)","explanation":"Sri Lanka has two capitals."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-03","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"Sri Lankan Tamils launched their movement to demand:","options":["foreign aid","recognition of Tamil as official language + regional autonomy + equal opportunity","colonial protection","British annexation"],"answer":"recognition of Tamil as official language + regional autonomy + equal opportunity","explanation":"Tamil demands."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-03","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"Which decade saw the formation of armed Tamil organisations demanding independent Eelam?","options":["1950s","1960s","1980s","2000s"],"answer":"1980s","explanation":"By the 1980s several armed organisations formed."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-04","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"In Belgium, the third-tier 'community government' is unique because it is elected by:","options":["region of residence","language community no matter where they live","income level","occupation"],"answer":"language community no matter where they live","explanation":"Community government is by language."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"Brussels' equal representation was accepted by French-speakers IN EXCHANGE for:","options":["money","equal representation in the central government accepted by Dutch-speakers","tax cuts","new buildings"],"answer":"equal representation in the central government accepted by Dutch-speakers","explanation":"Mutual concession."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-04","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"What does the Belgian model show about COMPLEX systems?","options":["complexity always fails","sometimes complex constitutional design is needed for real social diversity","simpler is always better","complexity is illegal"],"answer":"sometimes complex constitutional design is needed for real social diversity","explanation":"Complexity = peace."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-05","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"The PRUDENTIAL reason for power-sharing focuses on:","options":["careful calculation of gains and losses","spirit of democracy","beauty","tradition"],"answer":"careful calculation of gains and losses","explanation":"Prudence = practical."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-06","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"In a system of 'checks and balances', the term BALANCES means:","options":["weights of money","each organ balances the powers of the others, none can dominate","accounting balances","balance of trade"],"answer":"each organ balances the powers of the others, none can dominate","explanation":"Mutual balancing."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-06","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"India's three-tier government includes Union, State and:","options":["foreign","local (panchayats and municipalities)","royal","caste"],"answer":"local (panchayats and municipalities)","explanation":"Local — third tier."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-06","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"In India, women's representation in panchayats is reserved at:","options":["10%","15%","at least 33%","75%"],"answer":"at least 33%","explanation":"73rd Amendment."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-06","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":1,"question":"The judges in India can:","options":["override Parliament's laws if they violate the Constitution","never check the legislature","appoint ministers","levy taxes"],"answer":"override Parliament's laws if they violate the Constitution","explanation":"Judicial review."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-06","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"In a democracy, ministers and government officials are responsible to:","options":["the army","Parliament or State Assemblies","the courts only","foreign powers"],"answer":"Parliament or State Assemblies","explanation":"Responsibility = democracy."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-CIV-PS-06","difficulty":"MEDIUM","cognitive_level":"APPLY","marks":2,"question":"Which is an example of pressure-group power in India?","options":["BJP winning elections","FICCI and CII influencing economic policy","Supreme Court verdict","Cabinet meeting"],"answer":"FICCI and CII influencing economic policy","explanation":"Industry pressure groups."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-01","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"Why is Brussels so important in Belgium and Europe?","answer":"Brussels is special on three counts: (i) It is the CAPITAL of Belgium and one of the most diverse cities in Europe — 80% French-speaking and 20% Dutch-speaking, so it reverses the country's overall balance. (ii) It is governed by a SEPARATE government with equal representation of both communities, an essential part of the Belgian power-sharing model. (iii) Most importantly, Brussels is the HEADQUARTERS of the European Union — host to the European Commission, Council and Parliament — making it Europe's political capital. The choice of Brussels as the EU capital is partly a tribute to Belgium's success in handling its diversity peacefully.","explanation":"Brussels: triple importance."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-02","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"Why was the Sri Lankan civil war such a turning point in the country's history?","answer":"The civil war (early 1980s to 2009) marked Sri Lanka's lowest point: (i) THOUSANDS were killed — estimated 70,000-100,000 deaths over a quarter-century. (ii) Many families were forced to leave the country as REFUGEES; thousands of others were displaced internally. (iii) The country's economic, social and cultural progress was set back by decades. (iv) The TRUST between Sinhala and Tamil communities, built over centuries of co-existence, was deeply damaged. (v) International concern over human rights affected Sri Lanka's standing in the world. After 2009, post-war reconciliation has been slow but the lesson is clear: power-sharing with minorities is not a luxury — it is the only sustainable way for diverse societies.","explanation":"Civil war as turning point."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-04","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"How does Belgium ensure that no single language community can take decisions UNILATERALLY?","answer":"Several mechanisms: (i) The number of Dutch and French ministers in the central cabinet must be EQUAL — no single language group has a numerical majority in cabinet decisions. (ii) Some special laws require the SUPPORT OF THE MAJORITY OF MEMBERS OF EACH LINGUISTIC GROUP — not just a simple majority of all members. So a law cannot pass over the objections of either community. (iii) The state governments of the two regions are NOT subordinate to the centre — they have constitutional autonomy. (iv) Brussels has equal representation. (v) The community government for cultural matters is based purely on language community. Together these checks prevent unilateral action by any group.","explanation":"Anti-unilateral safeguards."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-05","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"Discuss with examples why majoritarianism, even in a democracy, can be self-defeating.","answer":"In a democracy, the majority can use its numbers to take all the power and impose its will on minorities. But this approach is SELF-DEFEATING because: (i) It ALIENATES the minority, making them resort to extra-constitutional means (protest, secession, armed struggle). (ii) Society slides into CONFLICT, civil war, or terror — undermining national unity, security and economy. (iii) The MAJORITY itself suffers: economic ruin, deaths in war, international sanctions. EXAMPLES: SRI LANKA's Sinhala majoritarianism led to a 26-year civil war that hurt all communities. NORTHERN IRELAND's Protestant majoritarianism led to 30 years of 'troubles'. Even within history, FRANCE's revolutionary terror and GERMANY's interwar majoritarianism led to disaster. Tyranny of the majority is NOT just unfair to the minority — it ultimately destroys the majority too. Power-sharing is therefore the only sustainable approach in a diverse democracy.","explanation":"Majoritarianism backfires."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-06","difficulty":"MEDIUM","cognitive_level":"APPLY","marks":3,"question":"Show with three Indian examples how political parties and pressure groups share power in India.","answer":"(i) COALITION GOVERNMENTS — between 1989 and 2014, India had several coalition governments at the centre (NDA under Vajpayee from 1999-2004, UPA under Manmohan Singh from 2004-2014). Power was shared among multiple parties through alliance agreements. (ii) STATE-LEVEL ALLIANCES — Tamil Nadu's DMK and Congress have allied repeatedly; Maharashtra has seen BJP-Shiv Sena, NCP-Congress and various other coalitions. (iii) PRESSURE GROUPS — FICCI and CII (industry); All India Kisan Sabha and farmer movements (agriculture); CITU and BMS (workers); the Narmada Bachao Andolan (environment) — all influence policy decisions even when they don't contest elections. (iv) MEDIA AND CIVIL SOCIETY — newspapers, TV news, and citizens' groups shape public opinion that constrains governments. Together these prevent the concentration of power in any one party or group.","explanation":"Indian examples — parties and pressure groups."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-04","difficulty":"HARD","cognitive_level":"ANALYZE","marks":5,"question":"Compare Belgium's power-sharing model with the Indian three-tier government system. What lessons can each learn from the other?","answer":"BELGIUM has a complex model designed for ETHNIC-LINGUISTIC diversity: (i) equal Dutch–French ministers in the central cabinet; (ii) strong state governments for the two main linguistic regions; (iii) a separate Brussels government with equal representation; (iv) a unique COMMUNITY government for each language community handling culture, education and language. India's model is designed for a much LARGER and more DIVERSE country: (i) UNION government for national subjects; (ii) STATE governments for state subjects (28 states + 8 UTs); (iii) LOCAL bodies (panchayats and municipalities) under the 73rd / 74th Amendments. India also has horizontal sharing between Parliament, executive and judiciary, and reserved seats for SCs / STs / women. LESSONS BELGIUM CAN LEARN FROM INDIA — how to handle DEEP DIVERSITY (28 states, 22 official languages, multiple religions) without civil war; how to give space to social-group identity through reserved constituencies; the value of STRONG LOCAL GOVERNMENT for grass-roots democracy. LESSONS INDIA CAN LEARN FROM BELGIUM — formal recognition of LINGUISTIC autonomy beyond just states (e.g. community-level cultural bodies for major language groups); STRONGER PROTECTION against majoritarian decisions through dual-majority laws; equal representation in genuinely shared institutions. Both models show that there is no SINGLE design for diverse democracies — each must adapt to its own social geography, but both depend on the same principle: SHARE POWER, don't concentrate it.","explanation":"Belgium ↔ India lessons."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-05","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"Why is power-sharing called the very SPIRIT of democracy? Discuss with at least three forms of sharing.","answer":"Democracy means rule by the people — but the people are not one undivided block. They are a collection of social groups, regions, languages, classes and interests. If government works for only ONE group, it is not really government BY the people but by ONE part of them — which is no different from rule by a small minority. So sharing power is not just one feature of democracy among many; it IS what democracy means in practice. Citizens need to be CONSULTED on how they are governed; a legitimate government is one in which all citizens feel they have a STAKE in the system. THREE FORMS: (i) HORIZONTAL SHARING — between legislature, executive and judiciary, ensures no single organ becomes a tyrant. The Indian Supreme Court can strike down laws of Parliament; the executive is answerable to the Lok Sabha. Each organ checks the others — preserving the rule of law. (ii) VERTICAL SHARING — between Centre, State and Local governments — ensures that decisions on local matters are made by people closest to those matters, while national matters are decided at the centre. (iii) AMONG SOCIAL GROUPS — reserved seats for Scheduled Castes, Scheduled Tribes, women in panchayats; Belgium's Community Government — ensures that historically marginalised or distinct groups have a fair share in decision-making. (iv) AMONG POLITICAL PARTIES, PRESSURE GROUPS AND MOVEMENTS — multiple parties competing in elections; coalition governments; trade unions, farmer organisations and civil-society movements influencing policy. WHY THIS IS THE SPIRIT — without all these forms of sharing, power becomes concentrated in one organ, one level, one group or one party. With them, EVERY citizen has multiple ways to be heard. Sharing is therefore not an extra feature of democracy but its essence.","explanation":"Power-sharing as essence of democracy."},
]

# Economics — needs ~24 obj + ~15 subj
EXTRA_214 = [
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-01","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"For a prosperous Punjab farmer, which is the most likely development goal?","options":["foreign holiday","better minimum support prices and reliable electricity for irrigation","more weight","new colours"],"answer":"better minimum support prices and reliable electricity for irrigation","explanation":"Farmer's goals."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-01","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"For an urban unemployed youth, the immediate development goal is:","options":["a stable job","more food","retirement","tourism"],"answer":"a stable job","explanation":"Employment."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-01","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"Why might a rich businessman ALSO want non-material things like respect and security?","options":["money is unlimited","material wealth alone does not satisfy needs for dignity, freedom, family, safety","he wants more taxes","he is bored"],"answer":"material wealth alone does not satisfy needs for dignity, freedom, family, safety","explanation":"Even rich need non-material."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-02","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"In what currency is the World Bank's per capita income usually expressed?","options":["Indian rupees","Chinese yuan","US dollars","Japanese yen"],"answer":"US dollars","explanation":"USD."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-02","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"Why is per capita income calculated as total income divided by population?","options":["to make calculation easy","to give the AVERAGE income per person","to confuse readers","tradition"],"answer":"to give the AVERAGE income per person","explanation":"Average."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-02","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"Compared to total income, per capita income is better for:","options":["measuring trade","comparing countries of different sizes","computing taxes","measuring exports"],"answer":"comparing countries of different sizes","explanation":"Standardised measure."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-03","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"In two countries with the same per capita income, which difference matters most for ordinary people?","options":["national flag","income distribution and access to public services","language","trees"],"answer":"income distribution and access to public services","explanation":"Distribution + public services."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-03","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":1,"question":"In the textbook example, Country A and Country B with same average income (Rs 7500/month) differed mainly in:","options":["population","income distribution","language","colour"],"answer":"income distribution","explanation":"Inequality differed."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-04","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"Which is NOT a public facility?","options":["state-run primary school","public bus","private gold ornaments","public drinking-water tap"],"answer":"private gold ornaments","explanation":"Private good."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"Why are public health centres especially important?","options":["they are free for the rich","they provide health care to those who cannot afford private alternatives","they are decorative","they collect taxes"],"answer":"they provide health care to those who cannot afford private alternatives","explanation":"Equity."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-05","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"India's overall LITERACY rate as of recent census is approximately:","options":["50%","65%","77%","90%"],"answer":"77%","explanation":"~77% national literacy."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-05","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"India's overall life expectancy at birth is approximately:","options":["50 years","60 years","70 years","85 years"],"answer":"70 years","explanation":"~70 years."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-05","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"Why is IMR considered a good indicator of overall public-health quality?","options":["babies are easy to count","it captures access to maternal care, immunisation, sanitation, nutrition — all major aspects of public health","it is set internationally","it has no relationship to health"],"answer":"it captures access to maternal care, immunisation, sanitation, nutrition — all major aspects of public health","explanation":"IMR captures many aspects."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-05","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"NET ATTENDANCE RATIO measures attendance for children of age:","options":["0–5","6–10","11–15","16–18"],"answer":"6–10","explanation":"Primary age group."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-05","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"Higher LIFE EXPECTANCY usually reflects:","options":["weather","good public health, nutrition, sanitation, education","industrial pollution","mineral wealth"],"answer":"good public health, nutrition, sanitation, education","explanation":"Many factors."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-06","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"PPP in 'PPP US$' for HDI stands for:","options":["Per Person Pay","Purchasing Power Parity","Public Policy Programme","Pro Public Pay"],"answer":"Purchasing Power Parity","explanation":"PPP adjusts for price levels."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-06","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"Why does HDI use PPP US$ rather than market exchange rate US$?","options":["arbitrary","to adjust for the fact that the same dollar buys different amounts in different countries","tradition","laziness"],"answer":"to adjust for the fact that the same dollar buys different amounts in different countries","explanation":"Cost of living adjustment."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-06","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"India ranks in the HDI:","options":["top 10","top 30","below 130 in recent reports","at 1"],"answer":"below 130 in recent reports","explanation":"~135 rank."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-06","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":1,"question":"Top HDI countries usually score around:","options":["0.50","0.70","0.96","1.20"],"answer":"0.96","explanation":"Top countries."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-07","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"India's groundwater is most stressed in which states?","options":["Kerala and Goa","Sikkim and Manipur","Punjab, Haryana, Rajasthan and parts of Tamil Nadu","Andaman and Nicobar"],"answer":"Punjab, Haryana, Rajasthan and parts of Tamil Nadu","explanation":"Stressed states."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-07","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"How does drip irrigation help sustainability?","options":["it uses more water","it delivers water directly to plant roots, using less water","it pollutes water","it is illegal"],"answer":"it delivers water directly to plant roots, using less water","explanation":"Water-efficient."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-07","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"The Brundtland Commission was named after:","options":["a US president","Norwegian Prime Minister Gro Harlem Brundtland","a UN secretary-general","a city"],"answer":"Norwegian Prime Minister Gro Harlem Brundtland","explanation":"Named after the chairperson."},
    {"type":"MCQ","outcome_code":"10-CBSE-SOC-ECO-DEV-07","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"Why is the Paris Climate Agreement (2015) important?","options":["it was signed in Paris only","it commits countries to limit warming to well below 2°C, requiring cooperation across borders","it bans tourism","it allows unlimited emissions"],"answer":"it commits countries to limit warming to well below 2°C, requiring cooperation across borders","explanation":"Global climate agreement."},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-SOC-ECO-DEV-02","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"India is in the high-income group as per the World Bank.","options":["True","False"],"answer":"False","explanation":"India is in low-middle income."},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-SOC-ECO-DEV-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"Public facilities create a 'level playing field' between rich and poor children.","options":["True","False"],"answer":"True","explanation":"Equal opportunity."},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-SOC-ECO-DEV-05","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"Net attendance ratio compares children attending school to all children of age ____ to ____.","answer":"6 to 10","explanation":"Primary age group."},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-SOC-ECO-DEV-06","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"HDI ranges from ____ to ____.","answer":"0 to 1","explanation":"0-1 scale."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-01","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"Give two examples where one person's development is another's destruction.","answer":"(i) DAMS — A large dam brings irrigation, drinking water and electricity to a Punjab farmer or a city dweller. But the same dam DISPLACES adivasi families from their ancestral land, drowns forests and disrupts ecosystems. What is development for one is destruction for the other. (ii) HIGHWAYS — A new highway helps a businessman move goods quickly and creates jobs. But for a wildlife corridor, the highway can fragment habitats and kill animals; for villagers, it can lead to dust, accidents and loss of farmland. (iii) AIR-CONDITIONING — Comfort for the user, but contributes to climate change for everyone. So the very same project can be development for some and destruction for others — which is why power-sharing in development decisions matters.","explanation":"Conflicting outcomes."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-02","difficulty":"MEDIUM","cognitive_level":"APPLY","marks":3,"question":"Country X has total income of US $ 500 billion and a population of 25 million. Country Y has total income of US $ 250 billion and a population of 5 million. Calculate per capita income of each. Which is richer on average?","answer":"Country X — per capita income = $500 billion / 25 million = $20,000. Country Y — per capita income = $250 billion / 5 million = $50,000. Although Country X has TWICE the total income of Country Y, Country Y is RICHER on average — its per capita income is 2.5 times that of Country X. This shows why per capita income, not total income, is the right comparison.","explanation":"Numerical illustration."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-03","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"Suppose a country's per capita income rises by 5% but inequality also rises sharply. Has development happened?","answer":"On the simple measure of per capita income, the country has GROWN. But DEVELOPMENT is not just income growth. If inequality rises sharply, it means the BENEFITS of growth are concentrated in a few hands while many remain in poverty. The poor may not see better schools, hospitals, or jobs. Indicators like IMR, literacy, life expectancy, women's education and access to public facilities may not improve. So while the country has GROWN economically, it has not necessarily DEVELOPED in the fuller sense. True development is INCLUSIVE — rising income that lifts everyone, especially the poorest. The textbook's distinction between mere income growth and broader development is exactly this point.","explanation":"Growth ≠ development."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-04","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"How can a state with limited resources still achieve good development outcomes?","answer":"By spending its resources WISELY on PUBLIC FACILITIES rather than concentrating wealth among a few. Specific strategies: (i) PRIORITISE PRIMARY HEALTH CENTRES and IMMUNISATION programmes — bringing IMR down dramatically. (ii) BUILD PUBLIC SCHOOLS in every village; provide free meals and books to encourage attendance — raising literacy and net attendance. (iii) Empower WOMEN through education and small-business support — multipliers across generations. (iv) PROVIDE CLEAN DRINKING WATER, sanitation and electricity. (v) USE GOVERNMENT MACHINERY honestly — corruption diverts resources from public services. KERALA is the proof: with lower per capita income than Haryana, it has invested decisively in public health and education and now has far better human development outcomes. Costa Rica, Sri Lanka and Vietnam have done similarly at the national level. Limited resources are not a destiny — wise public spending makes the difference.","explanation":"Smart spending wins."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-05","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"What does Kerala's experience teach us about development?","answer":"Kerala has lower per capita income than Haryana, but: lower IMR (~7 vs ~30), higher LITERACY rate (one of the highest in India), higher net attendance, higher life expectancy at birth. The reasons: Kerala has invested HEAVILY in PUBLIC HEALTH — primary health centres in every village, immunisation drives, maternal care; in PUBLIC EDUCATION — good public schools, free meals, public libraries, women's education; in WOMEN'S EMPOWERMENT — Kerala women are among the most educated in India, raising the next generation's outcomes. The lesson: HOW INCOME IS SPENT — on public facilities — matters as much as how MUCH income there is. A country or state can deliver high human development at lower per capita income through careful public investment.","explanation":"Kerala's lesson."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-06","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"How does the HDI capture more about development than per capita income alone?","answer":"PER CAPITA INCOME captures only the AVERAGE economic well-being of a country. The HDI adds two more dimensions: (i) HEALTH, measured by life expectancy at birth — captures sanitation, nutrition, public health, maternal care. (ii) EDUCATION, measured by mean and expected years of schooling — captures literacy, school attendance and educational opportunity. The three are then COMBINED into a single index between 0 and 1. So a country with high income but low life expectancy or schooling will score lower on HDI than its income alone suggests; a country with moderate income but excellent health and education (e.g. Sri Lanka, Costa Rica) can score better on HDI than its income alone would suggest. The HDI captures the LIVED reality of well-being, not just GDP.","explanation":"HDI = beyond income."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-07","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"Why is groundwater management one of India's biggest sustainability challenges?","answer":"India is the WORLD'S LARGEST groundwater extractor — pumping more water from below the ground than any other country. (i) In Punjab, Haryana, Rajasthan and parts of Tamil Nadu, water tables are FALLING by 2-3 metres every year because pumping outpaces rains. (ii) Wells go DEEPER and DEEPER, drying up old shallow wells used by poorer farmers. (iii) Saline water intrudes from the sea in coastal Tamil Nadu and Gujarat. (iv) Free or heavily subsidised electricity to farmers encourages over-pumping. (v) Water-hungry crops like rice and sugarcane in unsuitable regions add pressure. SOLUTIONS: rainwater harvesting; drip and sprinkler irrigation; rational pricing of electricity and water; switching to water-efficient crops; watershed management at panchayat level; restoration of village ponds. Without action, the country's most basic resource for food and life will collapse. Groundwater is therefore at the heart of India's sustainability challenge.","explanation":"Groundwater crisis + solutions."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-03","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"Discuss why per capita income is a useful but limited measure of development. What complementary indicators are needed?","answer":"Per capita income — total income divided by population — is USEFUL because: (i) it provides a standardised comparison across countries of different sizes; (ii) it captures the AVERAGE economic well-being; (iii) it is widely available and easy to interpret. The World Bank uses it to classify countries as high / middle / low income. But per capita income has SERIOUS LIMITATIONS as a measure of development: (i) IT HIDES INEQUALITY. Two countries with the same average can have very different distributions; in one most people live decent lives, in the other a few rich people lift the average while many remain poor. (ii) IT IGNORES PUBLIC FACILITIES. Many things people need — clean drinking water, public schools, public hospitals, safe streets, parks — cannot be bought individually in the market; they must be provided collectively. A country with poor public facilities is poorly developed even if its per capita income is high. (iii) IT IGNORES NON-MATERIAL DIMENSIONS — health, education, freedom, security, dignity. A society with high income but poor health, low literacy, high crime and authoritarian government is not really developed. (iv) IT DOES NOT CAPTURE SUSTAINABILITY. A country may have high present income but be using up its forests, groundwater and oil — undermining future generations. COMPLEMENTARY INDICATORS NEEDED: (a) Income inequality measures (e.g. Gini coefficient). (b) IMR and LIFE EXPECTANCY — for health. (c) LITERACY RATE and NET ATTENDANCE RATIO — for education. (d) Status of women — for gender equity. (e) HUMAN DEVELOPMENT INDEX (HDI) — combining income, health and education. (f) Sustainability indicators — air quality, water table, forest cover. Together these complement income to give a fuller picture of development.","explanation":"Income limits + supplements."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-07","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"'Sustainable development is essential for human survival.' Discuss with at least three examples drawn from India and the world.","answer":"Modern human societies depend on a stream of natural resources — water, air, soil, oil, minerals, forests, biodiversity. The pace of consumption today threatens to UNDERMINE the very foundation of human life. SUSTAINABLE DEVELOPMENT (Brundtland definition) means meeting present needs without compromising the ability of future generations to meet their own — both a moral duty and an economic survival strategy. EXAMPLES: (1) GROUNDWATER IN INDIA. India is the world's largest groundwater extractor; in Punjab, Haryana, Rajasthan and parts of Tamil Nadu, water is being pumped much faster than rains can refill it. Wells dry up; farmers go bankrupt; villages migrate. Without sustainable management — rainwater harvesting, drip irrigation, water pricing, watershed management — millions could face severe water crisis within a generation. (2) WORLD CRUDE OIL. At current rates, world oil reserves last only 35-40 years. Without transitioning to renewable energy and electric mobility, the global economy faces a hard landing — and climate change will worsen well before reserves are exhausted. India needs to invest heavily in solar, wind and EVs. (3) FORESTS WORLDWIDE. The Amazon, Congo, and Indonesian rainforests are being cleared at a rapid rate, releasing carbon, killing biodiversity and disrupting rainfall. The Forest Rights Act 2006 in India protects adivasi forest dwellers and gives them stake in forest conservation. (4) CLIMATE CHANGE. Environmental damage crosses borders; the Paris Climate Agreement (2015) commits countries to limit warming to well below 2°C — a problem that no country can solve alone. India's vulnerability includes more cyclones, melting glaciers and changes in monsoon. (5) PLASTIC POLLUTION. The world produces 400 million tonnes of plastic each year; only 10% is recycled. Without circular-economy reforms, our oceans will have more plastic than fish by 2050. ALL these examples show that DEVELOPMENT IGNORING SUSTAINABILITY IS BORROWING from our children — a debt no nation can pay back.","explanation":"Sustainability as survival."},
]


def main():
    db = SessionLocal()
    try:
        for ch_id, supp in [(197, EXTRA_197), (202, EXTRA_202), (209, EXTRA_209), (214, EXTRA_214)]:
            n = insert_for_chapter(db, ch_id, supp)
            print(f"  ch{ch_id}: inserted {n} new questions (skipped {len(supp) - n} as duplicates)")
    finally:
        db.close()


if __name__ == "__main__":
    main()
