"""Final batch — top up subjective questions for Civics and Economics chapters to reach 30-40 subjective."""

from sqlalchemy import select
from app.db.session import SessionLocal
from app.models.curriculum import BloomLevel, LearningOutcome
from app.models.question import Question, QuestionDifficulty, QuestionStatus, QuestionType

CREATED_BY_ID = 14


def _options(q):
    return {"choices": list(q["options"])} if q.get("options") else None


def insert_for_chapter(db, chapter_id, supp):
    outcome_map = {r.code: r.id for r in db.scalars(
        select(LearningOutcome).where(LearningOutcome.chapter_id == chapter_id)).all()}
    existing = {r.text for r in db.scalars(
        select(Question).where(Question.chapter_id == chapter_id)).all()}
    added = 0
    for q in supp:
        if q["question"] in existing: continue
        oc = q.get("outcome_code")
        db.add(Question(
            chapter_id=chapter_id, topic_id=None,
            outcome_id=outcome_map.get(oc) if oc else None, outcome_code=oc,
            type=QuestionType(q["type"]), difficulty=QuestionDifficulty(q["difficulty"]),
            status=QuestionStatus.APPROVED,
            cognitive_level=BloomLevel(q["cognitive_level"].lower()),
            text=q["question"], options=_options(q), correct_answer=q["answer"],
            explanation=q.get("explanation"), marks=int(q.get("marks", 1)),
            created_by_id=CREATED_BY_ID))
        added += 1
    db.commit()
    return added


# Civics — 8 more subjective
EXTRA_209 = [
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-01","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"Why was Brussels a special challenge in Belgian power-sharing?","answer":"Brussels reverses the country's overall language balance: while DUTCH-speakers are 59% of Belgium overall, in Brussels they are only 20% — a minority in the capital. French-speakers, who are 40% of the country overall, dominate Brussels at 80%. So whatever language formula was chosen at the national level produced an UNFAIR result in Brussels. The solution was to give BRUSSELS a SEPARATE government with EQUAL representation of both communities — the Dutch-speakers (a Brussels minority) get the same weight as the French-speakers. Combined with equal Dutch-French representation in the central cabinet, this DOUBLE EQUALITY ensures that no community feels permanently dominated.","explanation":"Brussels asymmetry handled."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-02","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"Why did Sri Lanka's Indian Tamils have a different historical experience from Sri Lankan Tamils?","answer":"Sri Lankan Tamils have lived in the island for many CENTURIES; they are concentrated in the north and east of Sri Lanka and consider it their homeland. Indian Tamils, by contrast, were brought from southern India to Sri Lanka by the British in the 19th and early 20th centuries to work on the TEA AND COFFEE PLANTATIONS in the central highlands. After independence in 1948, Sri Lankan governments treated the two sub-groups DIFFERENTLY — Indian Tamils faced citizenship problems for decades; many were sent back to India under bilateral agreements. Sri Lankan Tamils, while citizens, faced the language and other discriminations that led to the civil war. Both groups speak Tamil and most are Hindu, but their historical trajectories within Sri Lanka have been distinct.","explanation":"Two Tamil sub-groups."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-03","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"What were the early peaceful demands of Sri Lankan Tamils, and how did the state's response shape the conflict?","answer":"In the 1950s and 1960s, Tamil parties launched peaceful, parliamentary demands: (i) recognition of TAMIL as an official language alongside Sinhala; (ii) REGIONAL AUTONOMY for the Tamil-majority north and east of Sri Lanka; (iii) EQUAL OPPORTUNITY in jobs, education and government. Successive Sri Lankan governments REFUSED these demands. The 1956 Sinhala-only Act, preferential admission policies, and the 1972 constitution that fostered Buddhism deepened the alienation. By the 1980s, ARMED Tamil organisations emerged demanding a separate state — Tamil Eelam. The state's repeated REFUSAL to share power thus turned a peaceful constitutional movement into a 26-year civil war. The lesson: blocking peaceful demands creates the conditions for armed insurgency.","explanation":"From peaceful to armed."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-04","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"Why is the Belgian model called 'innovative'? Identify two specific innovations.","answer":"The Belgian model is called innovative because it created institutions that DID NOT exist before in democratic theory. (i) The COMMUNITY GOVERNMENT — a third tier of government elected by people of one language community no matter where they live. Unlike a usual federal state where governments are tied to TERRITORY, Belgium's community governments are tied to LANGUAGE — a person voting in Brussels but speaking French votes in the French community government, while a Dutch-speaker in Brussels votes in the Dutch community government. (ii) DUAL-MAJORITY voting on certain laws — laws need not just a majority of all parliamentarians but also a majority of EACH language group. Together these innovations protect linguistic minorities even where they live as residents in a region dominated by another language — a problem most older federal models could not solve.","explanation":"Two innovations."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-05","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"Why is power-sharing said to bring 'better outcomes' (the prudential reason)?","answer":"Power-sharing brings better outcomes because: (i) it REDUCES CONFLICT among social groups, since each group has a stake in the system and a way to be heard. (ii) Without conflict, the country has POLITICAL STABILITY — investors invest, businesses grow, schools run, hospitals stay open. (iii) Stability + diversity-friendly institutions = ECONOMIC GROWTH and PUBLIC GOODS. (iv) Avoiding civil war saves THOUSANDS of lives, prevents displacement, and keeps the economy on track. The CONTRAST with majoritarianism is stark: Sri Lanka, by hoarding power, suffered a 26-year civil war that cost lives and decades of growth. Belgium, by sharing power, kept its economy growing and became the EU capital. Power-sharing pays off — that is the prudential reason.","explanation":"Why prudential reason works."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-03","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"Trace the trajectory of Sri Lanka's MAJORITARIANISM and explain how it led to civil war.","answer":"Sri Lanka emerged as an independent country in 1948 with a complex ethnic mix: SINHALA-speaking Buddhist majority (74%), Tamil-speaking Hindu and Muslim minority (18% — Sri Lankan + Indian Tamils), and Christians (7%). MAJORITARIAN STAGE 1 — LANGUAGE. The 1956 Official Language Act recognised SINHALA as the only official language, disregarding Tamil. Tamil-speakers lost equal access to government services and jobs. STAGE 2 — JOBS & EDUCATION. Government policies gave PREFERENCE to Sinhala-speakers in admission to universities and recruitment to government posts. Tamil youth — many qualified — were systematically excluded. STAGE 3 — RELIGION. The 1972 constitution made the state PROTECT AND FOSTER BUDDHISM — a clear signal that the country belonged to one community. STAGE 4 — DENIED AUTONOMY. Tamil parties launched peaceful, constitutional demands for autonomy in their northern and eastern strongholds. Successive governments REFUSED. STAGE 5 — RADICALISATION. By the 1980s, several Tamil organisations were formed demanding an INDEPENDENT TAMIL EELAM. The largest was the Liberation Tigers of Tamil Eelam (LTTE). STAGE 6 — CIVIL WAR. From 1983 onwards, full-scale civil war raged: thousands killed, families forced into exile as refugees, the country's social, cultural and economic life devastated. The war finally ended in 2009 with massive human and economic costs to all sides. THE LESSON: each step of majoritarianism alienated more Tamils and made peaceful settlement harder. By the time political leaders realised what they had done, armed conflict had taken on a life of its own. Power-sharing FROM THE START — recognising Tamil as official language, granting regional autonomy, fair access to jobs — could have prevented decades of bloodshed.","explanation":"Step-by-step majoritarianism."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-06","difficulty":"HARD","cognitive_level":"APPLY","marks":5,"question":"Identify the four forms of power-sharing in modern democracies and discuss specific Indian institutional examples for each.","answer":"(1) HORIZONTAL — power distributed among legislature, executive and judiciary at the same level, with each checking the others. INDIAN EXAMPLES: Supreme Court can strike down unconstitutional laws of Parliament (e.g. it has done so with several Acts that violated fundamental rights); Lok Sabha can remove a government via no-confidence motion (used many times); the President can return Bills to Parliament with comments; the CAG audits government accounts independently. (2) VERTICAL — power distributed across UNION, STATE and LOCAL governments. INDIAN EXAMPLES: the Constitution divides subjects into Union List (defence, foreign affairs, currency), State List (police, agriculture, public health), and Concurrent List (education, marriage, criminal procedure); the 73rd and 74th Amendments (1992) give constitutional status to PANCHAYATS and MUNICIPALITIES, with their own elections, taxes and powers. (3) AMONG SOCIAL GROUPS — power shared with linguistic, religious or socially weaker groups. INDIAN EXAMPLES: reserved Lok Sabha and Vidhan Sabha SEATS for Scheduled Castes and Scheduled Tribes; one-third of seats in panchayats reserved for WOMEN; minority educational institutions; reserved jobs and university seats for SC/ST/OBC under Article 16; protection for tribal areas under Schedules V and VI. (4) AMONG POLITICAL PARTIES, PRESSURE GROUPS AND MOVEMENTS. INDIAN EXAMPLES: COALITION governments at the Centre (NDA under Vajpayee 1999-2004, UPA under Manmohan Singh 2004-2014); pre-poll alliances (BJP-Shiv Sena in Maharashtra, Congress-DMK in Tamil Nadu); pressure groups like FICCI (industry), AITUC (labour), Bharatiya Kisan Sangh (farmers), Narmada Bachao Andolan (environment); civil-society movements like the RTI movement that led to the Right to Information Act 2005. CONCLUSION — together these four forms create a dense web in which no single party, organ, level or community can dominate. India's democracy depends on the working of all four together.","explanation":"Four forms with Indian examples."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-CIV-PS-04","difficulty":"HARD","cognitive_level":"ANALYZE","marks":5,"question":"Compare the Belgian and Sri Lankan responses to ethnic diversity. What lessons do they hold for other diverse societies, including India?","answer":"BELGIUM — chose ACCOMMODATION. Faced with the rising demands of the Dutch-speaking majority (long economically subordinate to French-speakers), Belgian leaders RECOGNISED the diversity and amended the constitution four times between 1970 and 1993. They built: equal Dutch–French ministers in the central cabinet; strong autonomous state governments for Flanders and Wallonia; equal representation in Brussels; and a unique COMMUNITY GOVERNMENT for each language community. Result: NO civic war between the two communities; the country stayed together; Brussels became the capital of the European Union. SRI LANKA — chose MAJORITARIANISM. The 1956 Sinhala-only language Act, preferential jobs and university policies for Sinhala-speakers, and a constitution that protected Buddhism gradually alienated the Tamil minority. Tamil demands for autonomy were repeatedly refused. By the 1980s armed Tamil organisations demanded a separate state. Result: a 26-YEAR CIVIL WAR (1983-2009) — thousands killed, families displaced, the country's social and economic life devastated. LESSONS FOR DIVERSE SOCIETIES: (i) Power-sharing is not optional — diversity demands it. (ii) Constitutional engineering can SOLVE problems if leaders take diversity seriously. (iii) Refusing peaceful demands creates the conditions for armed conflict; once that happens, decades of progress are lost. (iv) Majoritarianism may LOOK attractive in the short run but undermines national unity and ultimately HURTS the majority too. FOR INDIA: India's far greater diversity (28 states, 22 official languages, multiple religions and castes) has so far been managed through power-sharing — federal structure, reserved constituencies, language-friendly states, multi-religious neutrality. The Belgian and Sri Lankan cases warn that any drift toward majoritarianism in India would be dangerous. Continuing to share power across states, communities and parties is essential for our democracy's survival and prosperity.","explanation":"Belgium vs Sri Lanka — lessons for India."},
]

# Economics — 12 more subjective
EXTRA_214 = [
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-01","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"List the eight categories of people the textbook uses to illustrate different development goals.","answer":"The textbook lists EIGHT categories: (1) landless rural labourer, (2) prosperous farmer from Punjab, (3) farmer who depends on rains, (4) urban unemployed youth, (5) rich urban businessman, (6) businessman from Kerala, (7) dam-displaced person, (8) adivasi from the Narmada valley. Each has a different — sometimes conflicting — idea of what development means: the labourer wants work, the businessman wants markets, the displaced person wants their land back, the adivasi wants forest-and-culture protection. The list shows that 'development' is plural — and that what is development for one can be destruction for another.","explanation":"Eight categories."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-01","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"Why are NON-MATERIAL goals important for everyone, including the rich?","answer":"Even people with high incomes need things money cannot fully buy: (i) RESPECT — being treated with dignity by neighbours, family, society. (ii) FREEDOM — to express opinions, to choose careers and partners, to practise one's religion. (iii) SECURITY — safety from crime and violence. (iv) HEALTH — fitness, mental wellbeing, longevity. (v) FAMILY AND COMMUNITY ties. (vi) ENVIRONMENT — clean air, water, beautiful surroundings. (vii) PURPOSE — meaningful work and a sense of contribution. A rich person living in fear, with broken family ties, polluted air and meaningless work is not really developed. Non-material goals therefore matter for ALL — not just the poor.","explanation":"Non-material universally important."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-02","difficulty":"MEDIUM","cognitive_level":"APPLY","marks":3,"question":"Calculate per capita income: Country X has a total income of $400 billion and population 40 million. Country Y has a total income of $300 billion and population 5 million. Compare.","answer":"Country X — per capita income = $400 billion / 40 million = $10,000 per person. Country Y — per capita income = $300 billion / 5 million = $60,000 per person. Although X has higher TOTAL income, Y is RICHER on average — its per capita income is six times that of X. By World Bank classification, Y is high-income, while X may be middle-income. This calculation shows why per capita income, not total income, is used to compare countries.","explanation":"PCI calculation example."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-03","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"Why do we say 'money cannot buy everything that matters for development'?","answer":"Many things essential to a good life cannot be bought individually with money: (i) CLEAN AIR — depends on collective action against pollution. (ii) PUBLIC SAFETY — depends on the police and rule of law. (iii) GOOD QUALITY PUBLIC HEALTH — even a rich person in a country with weak public hospitals has poor outcomes during a pandemic. (iv) GOOD PUBLIC SCHOOLS that integrate children of different backgrounds. (v) A CLEAN ENVIRONMENT, public parks, green cities. (vi) DIGNITY, equality before the law and freedom — not for sale. (vii) A STABLE CLIMATE. All these need PUBLIC FACILITIES and COLLECTIVE INSTITUTIONS, not individual purchase. So even at the same private income, life can be much better in a society that provides good public goods. Money alone is not enough.","explanation":"Money's limits."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-04","difficulty":"MEDIUM","cognitive_level":"APPLY","marks":3,"question":"Suggest five public facilities that an Indian state should prioritise for development.","answer":"(i) PRIMARY HEALTH CENTRES in every village + immunisation programmes — these reduce IMR dramatically. (ii) PUBLIC SCHOOLS with good teachers, free meals and books — raises literacy and net attendance. (iii) CLEAN DRINKING WATER and SANITATION (toilets, sewage) — major impact on disease and child mortality. (iv) ELECTRIFICATION and PUBLIC TRANSPORT — supports productivity and access to services. (v) GIRLS' EDUCATION + women's empowerment programmes — multipliers across generations. (vi) PUBLIC HOSPITALS with critical care; public libraries; public parks; police stations. (vii) DIGITAL public infrastructure — Aadhaar, payment system. KERALA is the textbook example: prioritising public health and education has given it human-development outcomes far better than its income alone would predict.","explanation":"Five priorities."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-05","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"What is Net Attendance Ratio? Why is it more useful than Gross Enrolment Rate?","answer":"NET ATTENDANCE RATIO (NAR) is the proportion of children aged 6–10 who attend school as a percentage of all children of that age. So if 90 out of 100 children aged 6-10 are attending primary school, NAR = 90%. It is a measure of HOW MANY of the right-age children are actually IN SCHOOL. GROSS ENROLMENT RATE just counts all enrolled — even those above or below the age range, or those enrolled but absent. NAR is more useful because: (i) it focuses on the relevant age group; (ii) it captures actual presence, not just paper enrolment; (iii) it tells us how successfully the education system is REACHING all children. Kerala has very high NAR; Bihar has lower NAR. NAR reveals real access to education better than total enrolment numbers.","explanation":"NAR vs gross enrolment."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-06","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"Why does India rank lower than Sri Lanka on HDI despite a comparable per capita income? What can India learn?","answer":"Sri Lanka has a per capita income comparable to India (within the same band) but a HIGHER HDI. Reasons: (i) Sri Lanka has invested decisively in PUBLIC HEALTH — universal primary health centres, free hospital care — leading to higher LIFE EXPECTANCY (~76 years vs India's ~70). (ii) Sri Lanka has invested heavily in PUBLIC EDUCATION — universal primary schooling, very high LITERACY (~93% vs India's ~77%). (iii) Sri Lanka's POLICIES on women's education and health have produced strong gender outcomes. WHAT INDIA CAN LEARN: that focused public investment in health and education at the primary level produces large gains in HDI, even at modest per capita income. Programmes like Ayushman Bharat (health), midday meals (school attendance) and Beti Bachao Beti Padhao (girl-child) point in the right direction; consistent and well-targeted public investment is the path forward.","explanation":"India ↔ Sri Lanka."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-07","difficulty":"MEDIUM","cognitive_level":"APPLY","marks":3,"question":"Suggest three sustainable practices a school can adopt.","answer":"(i) RAINWATER HARVESTING — install simple roof-water collection systems that fill underground tanks, reducing dependence on groundwater and providing drinking and washing water. (ii) SOLAR POWER — install rooftop solar panels for school electricity; the savings can fund teaching aids; teaches students about renewable energy. (iii) WASTE SEGREGATION + COMPOSTING — separate organic waste, paper, plastic; compost organic waste for the school garden; teach reduce-reuse-recycle. (iv) SCHOOL KITCHEN GARDEN — grow vegetables and herbs for the midday meal. (v) NO SINGLE-USE PLASTIC. (vi) Plant native trees in the school compound. (vii) Teach climate change in subjects across the curriculum. Together these turn the school into a working model of sustainability.","explanation":"School-level sustainability."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-04","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"Why are public facilities sometimes called 'great equalisers'?","answer":"Public facilities are 'great equalisers' because they make basic services — schools, hospitals, water, transport — available to ALL citizens regardless of family income. (i) A poor child going to a good public school has the same chance of learning as a rich child going to a private one. (ii) A pregnant woman from a poor family can use the public hospital with the same maternal care as a rich one in a private clinic. (iii) Cleaning of public streets, public transport, public libraries — all reach everyone. By contrast, where public facilities are weak, the rich buy private alternatives but the poor have nothing. Strong public facilities therefore create a LEVEL PLAYING FIELD, allowing talent from any background to flourish. The Kerala model and the Nordic countries are examples of this 'great equaliser' principle in action.","explanation":"Public facilities = equality."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-02","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"How does the World Bank classify countries by income? Discuss with thresholds and India's place.","answer":"The World Bank, in its annual WORLD DEVELOPMENT REPORT, classifies countries into FOUR income groups based on per capita Gross National Income (GNI) in US dollars: (i) HIGH-INCOME — per capita GNI ABOVE about US $13,205 in the most recent data (with the older 'rich country' threshold around US $49,300 for 'developed' status); these include Norway, Switzerland, USA, Japan, etc. (ii) UPPER-MIDDLE INCOME — per capita GNI between about US $4,256 and US $13,205. China, Brazil, Russia. (iii) LOWER-MIDDLE INCOME — per capita GNI between about US $1,086 and US $4,255. INDIA falls in this category, along with the Philippines, Egypt, Bangladesh and Vietnam. (iv) LOW-INCOME — per capita GNI BELOW about US $1,085. Mostly in sub-Saharan Africa. The thresholds are revised every year as world prices and incomes change. India's classification means: (a) we have left the lowest income group; (b) we are still well below the rich-country threshold; (c) the path forward is consistent growth + careful public investment to raise human-development outcomes. The World Bank classification is useful for comparison but, as discussed, per capita income alone is not enough — HDI and other indicators give a fuller picture.","explanation":"World Bank groups + thresholds."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-05","difficulty":"HARD","cognitive_level":"ANALYZE","marks":5,"question":"Compare the development indicators of Kerala, Haryana and Bihar in detail. What does this comparison teach us?","answer":"PER CAPITA INCOME — Haryana highest, Kerala middle, Bihar lowest. By income alone Haryana is ahead. INFANT MORTALITY RATE (IMR) — Kerala lowest (~7 per 1000 live births), Haryana ~30, Bihar ~32. On this critical health indicator, KERALA leads despite lower income. LITERACY RATE — Kerala highest in India (over 95%), Haryana middle (around 76%), Bihar lowest (around 62%). NET ATTENDANCE RATIO of 6-10-year-olds — same pattern; Kerala highest, Bihar lowest. LIFE EXPECTANCY at birth — Kerala highest (~75 years); India average ~70; Bihar lower. WHY KERALA LEADS DESPITE LOWER INCOME: Kerala has invested decisively in (i) PUBLIC HEALTH — primary health centres in every village, immunisation drives, maternal care; (ii) PUBLIC EDUCATION — high-quality public schools, midday meals, free books, public libraries; (iii) WOMEN'S EMPOWERMENT — women's literacy and labour-force participation are among the highest in India, raising the next generation's outcomes; (iv) LAND REFORMS in the 1960s gave land to the tiller, building rural prosperity; (v) STRONG GRAM-SABHA institutions and active civil society. WHY BIHAR LAGS — historically lower income compounded by weaker public services, low literacy that perpetuates poverty, and political turbulence. WHAT THIS COMPARISON TEACHES — (a) HOW INCOME IS SPENT matters as much as how MUCH income there is. (b) Public investment in HEALTH and EDUCATION is the single most effective lever for human development. (c) The Kerala model is replicable — Bihar and other lagging states can rise through similar investments. (d) Women's empowerment is central to overall development. (e) Income alone cannot tell us whether a society is developed; we need a fuller set of indicators.","explanation":"Three-state in-depth."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-SOC-ECO-DEV-06","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"Discuss the strengths and limitations of the Human Development Index as a measure of development.","answer":"STRENGTHS: (i) HDI captures THREE essential dimensions of well-being — INCOME, HEALTH (life expectancy), and EDUCATION (mean and expected years of schooling) — far more comprehensive than per capita income alone. (ii) PUBLISHED ANNUALLY by the UNDP, with consistent methodology, allowing comparison across countries and over time. (iii) Available on a single 0–1 SCALE that is easy to understand and to communicate. (iv) Recognised globally by governments, scholars and the press. (v) Has SHIFTED public discussion from purely economic growth to broader well-being. LIMITATIONS: (i) HDI does NOT capture INEQUALITY directly; a country with high HDI may still have major gaps between rich and poor. (UNDP has therefore introduced the INEQUALITY-ADJUSTED HDI as a complement.) (ii) Does not capture FREEDOM, DEMOCRACY or HUMAN RIGHTS — a wealthy authoritarian country can score high on HDI. (iii) Does not capture ENVIRONMENTAL SUSTAINABILITY — a country that scores well today may be using up its natural resources, ruining its long-run future. (iv) Does not capture GENDER GAPS, ETHNIC INEQUITIES, or other group-based disparities. (UNDP has separate Gender Inequality Index, Multidimensional Poverty Index.) (v) Mean / expected years of schooling do not capture quality of education. (vi) Uses national averages, hiding sub-national variation (state-level HDIs help). WHY STILL USEFUL: despite its limitations, HDI captures FAR MORE of life quality than per capita income alone, and has driven a worldwide shift toward broader development thinking. Used alongside complementary indicators (inequality, environment, gender, freedom), it remains the most practical single measure of development we have.","explanation":"HDI strengths + limits."},
]


def main():
    db = SessionLocal()
    try:
        for ch_id, supp in [(209, EXTRA_209), (214, EXTRA_214)]:
            n = insert_for_chapter(db, ch_id, supp)
            print(f"  ch{ch_id}: inserted {n} new questions (skipped {len(supp) - n} as duplicates)")
    finally:
        db.close()


if __name__ == "__main__":
    main()
