"""Top up question banks for the two CBSE Class 10 English Ch 1 chapters to reach 100 obj + 30-40 subj."""

from sqlalchemy import select
from app.db.session import SessionLocal
from app.models.curriculum import BloomLevel, LearningOutcome
from app.models.question import Question, QuestionDifficulty, QuestionStatus, QuestionType

CREATED_BY_ID = 14


def _options(q):
    return {"choices": list(q["options"])} if q.get("options") else None


def insert_for_chapter(db, chapter_id, supp):
    outcome_map = {r.code: r.id for r in db.scalars(
        select(LearningOutcome).where(LearningOutcome.chapter_id == chapter_id)).all()}
    existing = {r.text for r in db.scalars(
        select(Question).where(Question.chapter_id == chapter_id)).all()}
    added = 0
    for q in supp:
        if q["question"] in existing: continue
        oc = q.get("outcome_code")
        db.add(Question(
            chapter_id=chapter_id, topic_id=None,
            outcome_id=outcome_map.get(oc) if oc else None, outcome_code=oc,
            type=QuestionType(q["type"]), difficulty=QuestionDifficulty(q["difficulty"]),
            status=QuestionStatus.APPROVED,
            cognitive_level=BloomLevel(q["cognitive_level"].lower()),
            text=q["question"], options=_options(q), correct_answer=q["answer"],
            explanation=q.get("explanation"), marks=int(q.get("marks", 1)),
            created_by_id=CREATED_BY_ID))
        added += 1
    db.commit()
    return added


# ch219 — needs +14 subjective
EXTRA_219 = [
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-LTG-02","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"Why is rainfall so important to Lencho's family at the beginning of the story?","answer":"Lencho's family lives on a hillside farm in Mexico that DEPENDS ENTIRELY on the corn crop. The story opens with Lencho looking down at his field of grown corn dotted with the flowers that PROMISE A GOOD HARVEST — but the field needs ONE THING to bring the crop to fullness: a GOOD SHOWER OF RAIN. Without rain the harvest will fail and the family will starve. So the rain is not a luxury but a life-and-death matter; the family welcomes the first downpour as a sign of survival.","explanation":"Rain = survival."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-LTG-04","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"What does the postmaster's response to the letter reveal about him as a person?","answer":"The postmaster is a 'fat, amiable fellow' whose first reaction to the letter is to LAUGH — at the simplicity of an envelope addressed to GOD. But he quickly TURNS SERIOUS. He decides he does NOT want to SHAKE Lencho's faith. He treats the letter SERIOUSLY, organises a collection from his employees, contributes part of his OWN salary, and signs the reply 'GOD'. His response reveals: (i) RESPECT for another's beliefs even when he doesn't share them; (ii) PRACTICAL COMPASSION — he doesn't just feel sorry for Lencho, he ACTS; (iii) GENEROSITY without expectation — he sends the money anonymously; (iv) HUMILITY — he is willing to make a small loss to preserve another man's faith. He is the moral centre of the story.","explanation":"Postmaster's character."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-LTG-06","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"Was Lencho fair in his judgement of the post-office staff at the end of the story? Why or why not?","answer":"Lencho was NOT fair. His judgement is the central irony of the story — the very people who, moved by his faith, contributed their OWN money to help him, are accused by him of being 'a bunch of crooks'. He COULD NOT IMAGINE that ordinary people would have helped him; his world-view is so RIGID that any explanation other than divine intervention is unthinkable. So when the money comes short of the requested 100 pesos, his only available explanation is THEFT. The reader sees what Lencho cannot. His judgement reveals the danger of a faith so total that it cannot recognise human kindness; ironically, the very strength of his belief blinds him to the goodness of those around him.","explanation":"Unfair judgement."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-LTG-08","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"What lessons can the modern reader draw from 'A Letter to God'?","answer":"Several lessons: (i) FAITH can be a source of strength but must be balanced with the ability to RECOGNISE HUMAN KINDNESS. (ii) HUMAN COMPASSION exists in unexpected places — even strangers, even people we dismiss with a laugh, can be moved to act. (iii) PERCEPTION matters as much as fact — Lencho cannot 'see' the human help; we too may misjudge those who help us. (iv) IRONY is built into life — we often misunderstand the very things that save us. (v) GENEROSITY DOES NOT NEED ACKNOWLEDGEMENT — the postmaster's kindness is its own reward, even when misjudged. (vi) Even the most religious person needs HUMILITY — the world has more good in it than any one world-view can capture.","explanation":"Modern lessons."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-LTG-07","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"What is 'magical realism' and how does 'A Letter to God' fit the tradition?","answer":"MAGICAL REALISM is a Latin American literary tradition (associated with writers like Gabriel García Márquez, Jorge Luis Borges, Isabel Allende) in which the EVERYDAY mixes seamlessly with the MIRACULOUS. Realistic settings (a farm, a post office) host magical or supernatural events, presented in a matter-of-fact tone. 'A LETTER TO GOD' fits the tradition because it places a MIRACULOUS REQUEST (a letter posted to God) inside a perfectly REALISTIC setting (a small Mexican farm and a post office). Lencho's faith treats God as if He receives mail; the postmaster treats the letter as something that must be honoured. The tone is calm, almost folkloric. The READER is left to decide whether the answer was a miracle (God working through humans) or human compassion alone — the story holds the two together. This is the hallmark of magical realism.","explanation":"Magical realism."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-DOS-01","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"Describe the tiny moment that 'Dust of Snow' captures.","answer":"The poem records ONE tiny moment in a winter day. The speaker is walking under a HEMLOCK TREE — a poisonous evergreen tree often associated with sadness in literature. A CROW lands on a branch above him. The crow's weight shakes the branch and DUSTS the speaker with snow — a fine fall of snowflakes, an accidental, unsought-for gift. That tiny moment of cold flakes from a 'dark' bird on a 'dark' tree somehow LIFTS THE SPEAKER'S MOOD. A part of the day he had been REGRETTING (he had 'rued' it) is suddenly SAVED. The whole poem is just this moment — eight lines, one sentence, one mood-change.","explanation":"The moment captured."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-DOS-02","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"What does 'Dust of Snow' suggest about the role of NATURE in human life?","answer":"The poem suggests that NATURE is a quiet, often unnoticed HEALER. It does not always give grand sunsets or dramatic vistas — sometimes it gives a tiny, unsought-for moment that turns a 'rued' day into a SAVED one. The poem also suggests that the 'gloomy' parts of nature (a crow, a hemlock tree) are NOT WHAT THEY SEEM — even from dark sources, joy and renewal can come. Nature is generous in WAYS WE DON'T EXPECT and through CHANNELS we don't choose. To benefit from this gift, we have to be PRESENT — willing to notice what falls into our awareness rather than what we sought.","explanation":"Nature as quiet healer."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-DOS-03","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"List the key vocabulary of 'Dust of Snow' and give the meaning of each.","answer":"(i) HEMLOCK — a poisonous evergreen tree (in classical antiquity, the poison given to Socrates). (ii) RUED — past tense of 'rue': to feel regret about (a day, an action). (iii) DUST OF SNOW — a small, light fall of snowflakes shaken loose, like dust. (iv) BORE — past tense of 'bear': to carry. (v) Beyond these, the poem uses simple, everyday English: 'crow', 'snow', 'tree', 'change', 'mood', 'heart', 'day'. The simplicity of the vocabulary matches the simplicity of the moment; the difficulty is not in WORDS but in MEANING.","explanation":"Vocabulary."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-FAI-01","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"What is the structure of 'Fire and Ice', and what kind of voice does it use?","answer":"'Fire and Ice' has NINE SHORT LINES. It uses an irregular but consistent rhyme scheme (roughly ABAABCBCB) — Frost rhymes 'fire/desire', 'ice/twice/suffice', 'great/hate'. The CONTRAST between fire and ice is the structural backbone: stanza-like halves built around the two destructive forces. The VOICE is conversational, almost casual — phrases like 'Some say', 'From what I've tasted', 'I think I know enough' make it feel as if the speaker is THINKING ALOUD, weighing the options. The tone is CALM and PHILOSOPHICAL — and that calmness, paired with the apocalyptic content, makes the poem more chilling, not less.","explanation":"Structure + voice."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-FAI-03","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"How does 'Fire and Ice' speak to the modern world?","answer":"Frost wrote 'Fire and Ice' in 1920, but its argument is more relevant than ever: (i) CLIMATE CHANGE is fire — driven by human DESIRE (consumption, growth at any cost). The world is heating up because of our refusal to limit our wants. (ii) WAR AND DIVISION are ice — driven by human HATE (ethnic, religious, national hatreds, slow-burning grudges). From the World Wars to today's conflicts, much destruction is the product of slow-frozen hate. (iii) PERSONAL LIFE — even at the smallest scale, our families and selves can be destroyed by uncontrolled DESIRE or accumulated HATE. The poem is a WARNING at every scale — global, civic, personal — and a CALL to control our own fire and ice before they end our world.","explanation":"Modern relevance."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-ENG-LTG-06","difficulty":"HARD","cognitive_level":"ANALYZE","marks":5,"question":"Compare Lencho with the postmaster in detail. What does each character represent?","answer":"LENCHO is a hard-working farmer of UNSHAKEABLE FAITH. After the hailstorm destroys his crop, he turns DIRECTLY to God — writing a letter for 100 pesos so he can plant his fields again. His faith is so simple and so TOTAL that he does not need a long address; 'To God' is enough. He is also DECISIVE and PRACTICAL — naming a specific amount with a specific purpose. But he is also STUBBORN and SUSPICIOUS — when only 70 pesos arrives, he immediately accuses the post office staff of theft. He CANNOT IMAGINE that ordinary humans would have helped him. WHAT HE REPRESENTS — Lencho stands for the SIMPLE, RIGID believer — strong in faith but blind to the human kindness that may answer prayers. He is also the EVERYMAN — his name is the familiar form of 'Lorenzo', and his story speaks to anyone with deep convictions. THE POSTMASTER is a 'fat, amiable fellow' whose first reaction is to LAUGH — but who quickly turns serious because he RESPECTS Lencho's faith. He is COMPASSIONATE in PRACTICE — he organises a collection, contributes from his own salary, and signs the reply 'God'. He acts ANONYMOUSLY, expecting no thanks. WHAT HE REPRESENTS — the postmaster stands for the QUIET, EVERYDAY HUMANIST — non-religious or differently religious, but capable of generous action across belief systems. He is the MORAL CENTRE of the story. CONTRAST — Lencho's goodness is INTERNAL (faith); the postmaster's is EXTERNAL (action). Tragically, Lencho cannot see that the postmaster's action is real goodness — and accuses him. The story uses the contrast to teach that BOTH kinds of goodness exist, and that neither alone is enough. We need both faith and the eyes to see the help that actually comes.","explanation":"Two characters compared."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-ENG-FAI-02","difficulty":"HARD","cognitive_level":"ANALYZE","marks":5,"question":"Discuss the symbolism of FIRE and ICE in Frost's poem. How effective is the symbolism?","answer":"Frost's poem hinges on a simple but powerful symbolic equation. FIRE = DESIRE. Fire is HOT, CONSUMING, ALL-OR-NOTHING. It burns what it touches and demands more fuel. Desire — lust, greed, ambition without limit — works the same way: it consumes the person, the family, the resources around it; it always wants more; it ends only when nothing is left to burn. ICE = HATE. Ice is COLD, SLOW, DEADENING. It does not destroy quickly; it freezes, cracks, kills slowly. Hate works the same way: it cools relationships, freezes compassion, hardens the heart, and outlasts the things that should have moved on. Slow but relentless. WHY THESE PARTICULAR SYMBOLS? Frost picks two NATURAL forces that are PHYSICALLY OPPOSITE (hot vs cold) yet BOTH DESTRUCTIVE. By linking them to human emotions, he shows that emotions can take many forms — explosive or freezing — yet do the same work of ENDING. The reader recognises both forces in their own life, in society, in history. EFFECTIVENESS — the symbolism is highly effective for several reasons. (i) IT IS UNIVERSAL — every reader knows fire, knows ice, knows desire, knows hate. (ii) IT IS SHORT AND VIVID — nine lines do the work that a sermon could not. (iii) IT REFUSES TO RANK — Frost does not say one is worse than the other, leaving the reader to ASK WHICH IS OPERATING IN THEIR OWN LIFE. (iv) IT BRIDGES PHYSICAL AND MORAL — natural disasters and human emotions are made parallel. (v) IT PERSISTS — the poem feels true a century after it was written, applying to climate change (fire/desire) and global conflict (ice/hate). Frost's symbolism is therefore one of the cleanest, most powerful uses of physical force as moral lesson in modern poetry.","explanation":"Symbolism analysed."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-ENG-DOS-02","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"How does Frost transform 'gloomy' symbols into vehicles of joy in 'Dust of Snow'? What does this teach us about reading?","answer":"Frost's poem performs a quiet but stunning REVERSAL. It opens with two symbols that, in Western literary and folk tradition, are usually negative: the CROW (associated with bad luck, sadness, sometimes death) and the HEMLOCK TREE (a POISONOUS evergreen — in classical antiquity the poison given to Socrates). A reader trained on traditional symbolism would expect a poem about doom. INSTEAD, Frost makes these dark symbols deliver JOY. The crow's accidental movement dusts the speaker with snow; that tiny gift LIFTS the speaker's mood and SAVES part of a 'rued' day. WHY DOES FROST DO THIS? Several reasons. (i) To show that NATURE is generous in unexpected ways — gifts can come from sources we have written off. (ii) To suggest that LIFE ITSELF is more complex than our symbolic categories — what we call 'gloomy' may carry blessings; what we call 'lucky' may bring ruin. (iii) To teach a quiet HUMILITY — we should look at the world with fresh eyes, not just inherited associations. (iv) To enact what the poem describes — just as the speaker's mood is unexpectedly lifted by a 'dark' source, the READER's expectations are unexpectedly reversed by 'dark' symbols. The form mirrors the content. WHAT IT TEACHES US ABOUT READING — (i) DON'T ASSUME a poem's symbols mean what tradition says they mean; check what the poem actually does with them. (ii) PAY ATTENTION TO REVERSALS — the poet's choice of dark symbols followed by a happy outcome is a deliberate signal. (iii) READ AT MULTIPLE LEVELS — the literal moment (snow, crow, mood) AND the symbolic point (gloom may carry joy). (iv) APPLY TO LIFE — outside the poem too, we should be ready for unexpected gifts from unlikely sources. The poem is, in this sense, both a moment of beauty and a lesson in attentiveness. Eight lines deliver more than they appear to.","explanation":"Reversal + reading."},
]

# ch220 — needs +12 obj and +18 subj
EXTRA_220 = [
    # More objective
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-NM-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"Which national anthem was sung at Mandela's inauguration?","options":["Only the old anthem","Only 'Nkosi Sikelel' iAfrika'","Both the old anthem and the African anthem 'Nkosi Sikelel' iAfrika'","Neither"],"answer":"Both the old anthem and the African anthem 'Nkosi Sikelel' iAfrika'","explanation":"Both, side by side."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-NM-02","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"In what year was Mandela born?","options":["1900","1918","1925","1948"],"answer":"1918","explanation":"Born 1918."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-NM-02","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"In which region was Mandela born?","options":["Cape Town","Transkei","Johannesburg","Pretoria"],"answer":"Transkei","explanation":"Transkei region."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-NM-03","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"Mandela talks about TWIN obligations of every person. Which TWO?","options":["Work and play","Family and people","Rich and poor","Old and young"],"answer":"Family and people","explanation":"Twin obligations."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-NM-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"Mandela quotes that love is more natural to the human heart than:","options":["sleep","its opposite (hate)","food","water"],"answer":"its opposite (hate)","explanation":"Iconic quote."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-NM-06","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"What does the African anthem represent at the inauguration?","options":["a tribal hymn","the new free, multi-racial South Africa","an old colonial anthem","a religious hymn"],"answer":"the new free, multi-racial South Africa","explanation":"Symbol of new nation."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-NM-08","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"How long did Mandela serve as President of South Africa?","options":["one term (1994-99)","two terms","ten years","one year"],"answer":"one term (1994-99)","explanation":"One five-year term."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-NM-09","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"Mandela's autobiography 'Long Walk to Freedom' was published in:","options":["1948","1990","1994","2000"],"answer":"1994","explanation":"1994 publication."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-TZ-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"In what country was Leslie Norris born?","options":["Wales (United Kingdom)","South Africa","India","USA"],"answer":"Wales (United Kingdom)","explanation":"Welsh poet."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-TZ-02","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"In stanza 4 of the poem, where does the wild tiger snarl?","options":["near a temple","near a village","near the school","near the moon"],"answer":"near a village","explanation":"Tiger near village."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-TZ-03","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"What is the second-and-fourth-line rhyme called in poetry analysis?","options":["AABB rhyme","ABCB rhyme","ABAB rhyme","free verse"],"answer":"ABCB rhyme","explanation":"ABCB pattern."},
    {"type":"MCQ","outcome_code":"10-CBSE-ENG-NM-05","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"What does Mandela mean by saying 'to be FREE is not merely to cast off one's chains'?","options":["chains are decorative","freedom requires more than ending oppression — it requires respecting and ENHANCING others' freedom","chains are heavy","chains can be re-attached"],"answer":"freedom requires more than ending oppression — it requires respecting and ENHANCING others' freedom","explanation":"Mandela's deeper view."},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-ENG-NM-08","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"Mandela served two terms as President.","options":["True","False"],"answer":"False","explanation":"He served only one term (1994-99)."},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-ENG-TZ-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"Leslie Norris was a Welsh poet.","options":["True","False"],"answer":"True","explanation":"From Wales."},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-ENG-NM-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"The African concept 'I am because we are' is called ____.","answer":"ubuntu","explanation":"Ubuntu."},
    # Subjective
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-NM-01","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"Why was 10 May 1994 historically significant for South Africa?","answer":"10 May 1994 marked the formal end of THREE CENTURIES of WHITE RULE in South Africa — colonial conquest, segregation, and 46 years of formal APARTHEID since 1948. On that day, NELSON MANDELA was inaugurated as the FIRST BLACK PRESIDENT of South Africa, after winning the country's first multi-racial democratic election (27 April 1994). The new South African flag was raised; the African anthem 'Nkosi Sikelel' iAfrika' — once a CRIME for Mandela to sing — was sung as the anthem of the free nation. The day signalled the birth of a multi-racial, democratic South Africa and the world's leading example of peaceful transition from oppression to equality.","explanation":"Historic significance."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-NM-06","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"What symbols at the inauguration represented the new South Africa? Why were they chosen?","answer":"Several symbols at the inauguration ceremony embodied the new nation: (i) THE NEW FLAG with six colours combining South Africa's diverse heritage. (ii) The AFRICAN ANTHEM 'Nkosi Sikelel' iAfrika' sung alongside the OLD ANTHEM — uniting two musical traditions. (iii) THE TWO DEPUTIES — F.W. de Klerk (white) and Thabo Mbeki (black) — beside Mandela on stage, representing reconciliation. (iv) The SOUTH AFRICAN AIR FORCE FLY-PAST in the new colours — military pledge of allegiance to the democratic nation. (v) The use of MANDELA'S CLAN NAME 'Madiba' — honouring African tradition. WHY CHOSEN — these symbols said: this is no longer a country of one group ruling another; it is a SHARED HOME of all South Africans, weaving together African, European and other heritages into one nation. The very things that had been forbidden (the African anthem) or feared (a black president) were now CELEBRATED.","explanation":"Symbols of the new nation."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-NM-07","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"What does Mandela mean by the 'extraordinary human disaster' of apartheid? Was the wound deep?","answer":"Mandela calls apartheid 'AN EXTRAORDINARY HUMAN DISASTER' that created 'A DEEP AND LASTING WOUND' on South Africa and its people. The wound was MULTI-DIMENSIONAL: (i) POLITICAL — the denial of the vote, of citizenship, of representation; (ii) ECONOMIC — denial of decent jobs, education, land, leading to entrenched poverty; (iii) SOCIAL — forced separation, broken families, segregated public spaces; (iv) PSYCHOLOGICAL — the daily humiliation of being treated as inferior, the internalised inferiority that takes generations to heal. Mandela acknowledges the wound at the very moment of victory because he knows that HEALING begins with TRUTH. He pledges 'never, never and never again' shall South Africa experience the oppression of one by another — but he does not pretend the wound never happened. He balances grief and gratitude — the same struggle gave South Africa 'men of such extraordinary courage, wisdom and generosity'.","explanation":"Wound assessed."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-NM-08","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"What was Mandela's life like in prison?","answer":"Mandela was sentenced to life imprisonment on 12 JUNE 1964 and held mostly on ROBBEN ISLAND for 27 YEARS. Conditions were severe: he was assigned HARD LABOUR in a LIMESTONE QUARRY, breaking rocks day after day, which permanently damaged his eyes; he was confined to a tiny CELL where he slept on a thin mat; he was allowed only one VISITOR per six months and limited LETTERS. Despite this he REFUSED to be broken — he studied law, learned Afrikaans (the language of his jailers), led protests inside the prison, and SECRETLY WROTE much of his autobiography 'Long Walk to Freedom' in those years. He used the time to think deeply about reconciliation and to form the moral framework that would later guide his presidency. The 27 years became the foundation of his legend — a man who emerged from prison without bitterness, ready to rule.","explanation":"Prison years."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-TZ-02","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"How does the poem use STRONG VERBS to convey meaning?","answer":"Norris's poem uses powerful, action-rich verbs that do most of the work: PADS (caged tiger walks softly back and forth), STALKS (moves stealthily), SLIDES (moves smoothly through long grass), LURKS (waits hidden), SNARLS (makes a fierce growl), TERRORISES (frightens), HEARS (notices the patrol car), STARES (gazes at the brilliant stars). The verbs CARRY the contrast between caged and wild — soft, slow verbs for the cage (pads, ignores, hears, stares) and fierce, active verbs for the wild (slides, lurks, snarls, terrorises). The poet doesn't need to LECTURE about freedom; the verbs themselves SHOW it. The reader feels the tiger's movement (or lack of it) through the verbs alone.","explanation":"Verbs as carrier."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-TZ-03","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"List the key vocabulary of 'A Tiger in the Zoo' and give the meaning of each.","answer":"(i) STALKS — walks proudly, stealthily, like a hunter. (ii) PADS — soft cushions on a cat's foot; or to walk softly on those pads. (iii) LURKS — waits hidden, especially with intent to strike. (iv) SNARLS — makes a fierce, low growl. (v) TERRORISES — fills with fear. (vi) BAR-LIKE — like the bars of a cage; used of stripes. (vii) BRILLIANT — very bright; outstanding. (viii) WATER-HOLE — a small pool of water in the wild where animals come to drink. The vocabulary mixes simple and vivid words; the strong verbs do the heavy work of the poem.","explanation":"Vocabulary list."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-TZ-04","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"What does the tiger's gaze at the stars symbolise? Why is this image especially powerful?","answer":"At night, when visitors are gone and the city is silent, the caged tiger STARES AT THE BRILLIANT STARS. The stars symbolise FREEDOM — distant, eternal, unreachable. The cage cannot keep his EYES; his gaze still travels to the heavens. Yet his BODY remains trapped. WHY POWERFUL — (i) The stars are a UNIVERSAL symbol of distant freedom — every prisoner, in every era, has stared at the sky. The image links the tiger to all unfree beings. (ii) The CONTRAST between the cage (close, bounded, dark) and the stars (far, infinite, brilliant) is visually overpowering. (iii) The image suggests that EVEN IN CAPTIVITY, something free remains — the gaze, the longing, the dignity of looking outward. (iv) The image is the LAST in the poem, leaving the reader with a lingering picture rather than a stated conclusion — a true poet's choice. (v) It also echoes Mandela on Robben Island, who also gazed at the same stars — making the image's connection to the prose chapter especially deep.","explanation":"Stars as symbol."},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-ENG-NM-09","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"How does the chapter as a whole prepare the reader to think about FREEDOM?","answer":"The chapter pairs a great political autobiography with a small twenty-line poem so that the reader experiences FREEDOM at TWO SCALES. Mandela writes from the FREEDOM SIDE — the day a long imprisonment ends; the public ceremony; the long walk that brought him there. Norris writes from the CAPTIVITY SIDE — the imagined eye of a tiger pacing in a zoo, longing for jungle. The pairing prepares the reader to (i) UNDERSTAND that freedom is a HUGE political achievement won by generations of struggle (Mandela); (ii) FEEL what is LOST when freedom is denied even to a single creature (Norris); (iii) RECOGNISE that the OPPRESSOR is as unfree as the OPPRESSED — the cage diminishes both keeper and kept; (iv) APPLY these insights to our own lives and societies — to value the freedoms we have and to work for the freedom of those who lack it. The chapter thus makes 'freedom' a concrete, felt theme rather than an abstract word.","explanation":"Two-scale freedom."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-ENG-NM-03","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"Discuss Mandela's idea of the 'twin obligations' to family and to people. How did apartheid make both impossible?","answer":"Mandela writes that every person has TWO obligations in life: an OBLIGATION TO HIS FAMILY — his parents, his wife, his children — and an OBLIGATION TO HIS PEOPLE — his community, his country. In a JUST AND FREE society, both can be fulfilled together. A man can earn a living and raise his children while also serving his community as voter, citizen and worker. UNDER APARTHEID, BOTH WERE IMPOSSIBLE. To do duty to one's PEOPLE meant joining the struggle against an unjust state; that struggle led to PRISON, EXILE or DEATH. Children grew up without fathers — many ANC leaders were imprisoned or in exile for years; their wives carried double burdens. To do duty to one's FAMILY meant accepting apartheid quietly, finding a job within its limits, raising children inside the system — but this meant teaching your own children to ACCEPT INJUSTICE, to live as second-class citizens, to be daily humiliated. Both choices were impossible. Mandela himself paid this price — his marriage to Winnie suffered through 27 years of imprisonment; his children grew up without him. He acknowledges this loss in the autobiography: he was a TERRIBLE FATHER and HUSBAND in the conventional sense, BUT his choice to serve the people meant millions of OTHER families could one day live freely. The 'twin obligations' framework helps us see (i) the depth of apartheid's evil — it didn't just take political rights, it shattered the basic human task of being a parent, child, partner; (ii) the moral cost of the freedom struggle — those who fought paid in family life as well as in body; (iii) why Mandela's victory was for everyone — only in a free society can ordinary people fulfil both obligations naturally. His insight names a wound and a hope at once.","explanation":"Twin obligations."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-ENG-NM-04","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"Examine Mandela's view that 'love comes more naturally to the human heart than its opposite'. Is this view supported by the chapter?","answer":"Mandela writes that NO ONE IS BORN HATING another person because of skin colour or background; people LEARN to hate. And if they can be taught to hate, they can be TAUGHT TO LOVE — for love comes MORE NATURALLY to the human heart than its opposite. This is one of his most quoted lines. THE CHAPTER SUPPORTS IT in several ways. (i) MANDELA'S OWN EXAMPLE — emerging from 27 years of unjust imprisonment, he chose RECONCILIATION over revenge. He invited de Klerk (his white former opponent) as deputy, embraced his jailers, and championed a 'rainbow nation'. If hate were innate, his stance would be impossible after such suffering. (ii) THE POSTMASTER'S RESPONSE in 'A Letter to God' (the previous chapter) — a complete stranger moved to compassion across class and belief — shows the same instinct. (iii) THE TIGER POEM — even a caged creature retains DIGNITY, ignoring his oppressors rather than burning with hate; the heart's natural state is not destruction. (iv) THE TRUTH AND RECONCILIATION COMMISSION (which followed in 1995) was based on this premise: that perpetrators and victims could face each other, that public truth and apology could heal, and that South Africa could move forward without civil war. (v) BROADER HISTORY — Gandhi, Martin Luther King Jr., the Velvet Revolution, the fall of the Berlin Wall — all are examples of love (in the form of nonviolence, forgiveness, shared humanity) overcoming entrenched hate. POSSIBLE OBJECTIONS — one might argue that hate seems easier and more common; that some genocides and tribal wars suggest hate is deeply rooted. But Mandela's claim is not that hate is impossible — he acknowledges people LEARN to hate. His claim is that love is MORE NATURAL — closer to the heart's native state. The widespread teaching of hate (through propaganda, segregated schools, dehumanising language) is what makes hatred operative. Remove the teaching, expose the lie, and the heart returns to its natural openness. The chapter — and Mandela's own life — strongly support this view.","explanation":"Love vs hate examined."},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-ENG-TZ-02","difficulty":"HARD","cognitive_level":"ANALYZE","marks":5,"question":"Analyse the structure of 'A Tiger in the Zoo' as a study of contrast. How does the form serve the theme?","answer":"Norris's poem is a master-class in STRUCTURE serving THEME. The poem is just 5 stanzas × 4 lines = 20 lines. The structural choice is ALTERNATION between CAGED and WILD scenes. STANZA 1 (caged) — the tiger walking softly on PADS OF VELVET behind the BARS OF HIS CAGE. STANZA 2 (wild) — sliding through LONG GRASS in his natural element. STANZA 3 (caged) — IGNORING visitors who come to gawk at him. STANZA 4 (wild) — LURKING near a water-hole to ambush deer; or SNARLING near a village to terrorise its people. STANZA 5 (caged at night) — the city silent, the tiger STARING AT the BRILLIANT STARS — a gaze at distant freedom. HOW FORM SERVES THEME — (i) THE ALTERNATION FORCES THE READER to see the cage AGAINST the wild on every page. The contrast cannot be missed. The cage diminishes, the wild restores. (ii) THE FREQUENCY: 3 caged stanzas vs 2 wild stanzas — the cage WINS in real life; the tiger spends most of his time in confinement, the wild only as a memory. (iii) THE FINAL STANZA returns to the cage at night — leaving the reader with confinement, not freedom. The last image is the GAZE at the stars — a longing rather than a fulfilment. The structure thus enacts the situation: WE LIVE IN THE CAGE; we GLIMPSE the wild only in memory and imagination. (iv) THE RHYME (ABCB in each stanza) — the second and fourth lines rhyme, creating a quiet rhythm that doesn't overpower meaning. The rhyme is consistent enough to feel like the slow, repeated steps of a caged tiger pacing back and forth. (v) THE LINE LENGTH AND VERBS — short lines, strong verbs (pads, slides, lurks, snarls, terrorises, stares) — make the poem feel like the very movement of a tiger: each line a step, each verb a gesture. (vi) THE LACK OF EXPLICIT MORAL — the form leaves the JUDGEMENT to the reader, making it more powerful. CONCLUSION — Norris uses every formal choice — alternation, count, length, rhyme, verb, image — to make the reader FEEL the contrast between freedom and captivity. The poem's argument is the poem's form. Twenty lines do the work of a hundred.","explanation":"Structural analysis."},
]


def main():
    db = SessionLocal()
    try:
        for ch_id, supp in [(219, EXTRA_219), (220, EXTRA_220)]:
            n = insert_for_chapter(db, ch_id, supp)
            print(f"  ch{ch_id}: inserted {n} new questions (skipped {len(supp) - n} as duplicates)")
    finally:
        db.close()


if __name__ == "__main__":
    main()
