"""Top up question banks for ch237 and ch238 to reach 100 obj + 30-40 subj."""

from sqlalchemy import select
from app.db.session import SessionLocal
from app.models.curriculum import BloomLevel, LearningOutcome
from app.models.question import Question, QuestionDifficulty, QuestionStatus, QuestionType


def _options(q):
    return {"choices": list(q["options"])} if q.get("options") else None


def insert_for_chapter(db, chapter_id, supp):
    outcome_map = {r.code: r.id for r in db.scalars(
        select(LearningOutcome).where(LearningOutcome.chapter_id == chapter_id)).all()}
    existing = {r.text for r in db.scalars(
        select(Question).where(Question.chapter_id == chapter_id)).all()}
    added = 0
    for q in supp:
        if q["question"] in existing: continue
        oc = q.get("outcome_code")
        db.add(Question(
            chapter_id=chapter_id, topic_id=None,
            outcome_id=outcome_map.get(oc) if oc else None, outcome_code=oc,
            type=QuestionType(q["type"]), difficulty=QuestionDifficulty(q["difficulty"]),
            status=QuestionStatus.APPROVED,
            cognitive_level=BloomLevel(q["cognitive_level"].lower()),
            text=q["question"], options=_options(q), correct_answer=q["answer"],
            explanation=q.get("explanation"), marks=int(q.get("marks", 1)),
            created_by_id=14))
        added += 1
    db.commit()
    return added


# ===== ch237 (सूरदास के पद) — need +40 obj, +18 subj =====
EXTRA_237 = [
    # objective
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"सूरदास का जन्म-स्थान किसके पास है?","options":["वाराणसी","दिल्ली के पास सीही","मथुरा","आगरा"],"answer":"दिल्ली के पास सीही","explanation":"सीही जन्म-स्थान।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"अष्टछाप की स्थापना किसने की?","options":["वल्लभाचार्य","विट्ठलनाथ","रामानन्द","निंबार्क"],"answer":"विट्ठलनाथ","explanation":"वल्लभाचार्य के पुत्र।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"सूरदास की रचना 'साहित्य-लहरी' किस विषय पर है?","options":["राम-कथा","कृष्ण-काव्य का संग्रह","दर्शन","आत्मकथा"],"answer":"कृष्ण-काव्य का संग्रह","explanation":"साहित्य-लहरी।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-01","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"सूरदास की रचनाओं की मुख्य विषय-वस्तु क्या है?","options":["राम-कथा","कृष्ण-लीला और भक्ति","शिव-कथा","दर्शन"],"answer":"कृष्ण-लीला और भक्ति","explanation":"कृष्ण-काव्य।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-02","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"भ्रमरगीत प्रसंग में 'कृष्ण' कहाँ चले गए हैं?","options":["अयोध्या","द्वारका","मथुरा","लंका"],"answer":"मथुरा","explanation":"कृष्ण मथुरा गए।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-02","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"उद्धव गोपियों के सामने किसके माध्यम से बातें कहते हुए चित्रित हैं?","options":["राजा के","भौंरे (भ्रमर) के","फूलों के","कृष्ण के"],"answer":"भौंरे (भ्रमर) के","explanation":"भ्रमरगीत।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-02","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"उद्धव-गोपी संवाद कौन-सा बड़ा प्रश्न उठाता है?","options":["कौन धनी है","ज्ञान बनाम भक्ति","कौन शिव-भक्त है","कृष्ण कहाँ हैं"],"answer":"ज्ञान बनाम भक्ति","explanation":"मुख्य विमर्श।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-03","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"पहले पद में गोपियाँ अपने प्रेम की किस पर तुलना करती हैं?","options":["कमल पर","प्रेम-सागर पर — जिसमें वे डूब चुकी हैं","आकाश पर","नदी पर"],"answer":"प्रेम-सागर पर — जिसमें वे डूब चुकी हैं","explanation":"प्रेम-सागर का रूपक।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-03","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"पहले पद में 'पुरइन-पात' से उद्धव की कौन-सी विशेषता बतायी गयी है?","options":["रंग","आकार","निर्लिप्तता","आयु"],"answer":"निर्लिप्तता","explanation":"प्रेम-शून्य अछूता।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"दूसरे पद में 'गुड़ खाये गुलगुलि कतंड़' कहावत किस भाव को व्यक्त करती है?","options":["खुशी","प्रेम का मीठापन योग से कड़वा बन गया","सुगंध","अनुभव"],"answer":"प्रेम का मीठापन योग से कड़वा बन गया","explanation":"गुड़-गोबर भाव।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-04","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"दूसरे पद में गोपियाँ क्यों कहती हैं कि उद्धव का संदेश 'अप्राप्य' है?","options":["वह असुंदर है","योग गोपियों के प्रेम-स्वभाव से मेल नहीं खाता","वह कठिन है","वह छोटा है"],"answer":"योग गोपियों के प्रेम-स्वभाव से मेल नहीं खाता","explanation":"प्रकृति-असंगति।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-05","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"तीसरे पद में 'मधुर औषधि' किसका प्रतीक है?","options":["शहद का","कृष्ण-प्रेम का","दूध का","फल का"],"answer":"कृष्ण-प्रेम का","explanation":"मधुर = कृष्ण।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-05","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"तीसरे पद में 'कड़वी दवाई' किसका प्रतीक है?","options":["जहर","योग-शिक्षा (निर्गुण)","ज्वर","बुखार"],"answer":"योग-शिक्षा (निर्गुण)","explanation":"कड़वी = निर्गुण।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-06","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"चौथे पद में गोपियों के मन में क्या बदलाव आया है?","options":["खुशी","निराशा और शिकायत","भय","लोभ"],"answer":"निराशा और शिकायत","explanation":"बदलाव।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-06","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"चौथे पद में 'राजनीति' शब्द का सीधा अर्थ क्या है?","options":["कुछ भी नहीं","राज्य-संचालन की कलाएँ; नीतिशास्त्र","राजा का सिंहासन","विजय"],"answer":"राज्य-संचालन की कलाएँ; नीतिशास्त्र","explanation":"प्रत्यक्ष अर्थ।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-06","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"चौथे पद में किस पर सूक्ष्म व्यंग्य है?","options":["राजा-राजनीति पर","सत्ता-प्रेम के संबंध पर","भक्ति पर","ज्ञान पर"],"answer":"सत्ता-प्रेम के संबंध पर","explanation":"बहुस्तरीय व्यंग्य।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-07","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"पाठ का मुख्य रस वियोग-शृंगार क्यों है?","options":["क्योंकि गोपियाँ हँसती हैं","क्योंकि गोपियाँ कृष्ण के विरह में दुःखी हैं","क्योंकि लड़ाई होती है","क्योंकि भोजन है"],"answer":"क्योंकि गोपियाँ कृष्ण के विरह में दुःखी हैं","explanation":"विरह = वियोग।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-07","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"सूरदास के पदों की संगीतात्मकता का क्या प्रभाव है?","options":["कुछ नहीं","पद आज भी गाये जाते हैं और सदियों तक जीवित रहे","लम्बे हो जाते हैं","कठिन हो जाते हैं"],"answer":"पद आज भी गाये जाते हैं और सदियों तक जीवित रहे","explanation":"संगीतात्मकता।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-08","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"'सहसबाहु' का अर्थ क्या है?","options":["सहस्र-बाहु; एक राजा","कृष्ण","उद्धव","लक्ष्मण"],"answer":"सहस्र-बाहु; एक राजा","explanation":"सहसबाहु।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-08","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"'मानहुँ' शब्द का अर्थ क्या है?","options":["सम्मानित","जैसे; मानो","नहीं","कृपया"],"answer":"जैसे; मानो","explanation":"मानहुँ।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-08","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"'तपोबल' का अर्थ क्या है?","options":["तप का बल","कुछ नहीं","धन","पाप"],"answer":"तप का बल","explanation":"तपोबल।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-09","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"सूरदास के पदों की भावात्मक संरचना का सार क्या है?","options":["खुशी > दुःख","व्यंग्य > वियोग > समर्पण > शिकायत","प्रेम > घृणा","दिन > रात"],"answer":"व्यंग्य > वियोग > समर्पण > शिकायत","explanation":"चार चरण।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-09","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"सूरदास का संदेश आज भी प्रासंगिक क्यों है?","options":["इसमें मनोरंजन है","भावना और हृदय का स्थान बुद्धि से बड़ा है — यह आज भी सच है","भाषा कठिन है","लंबा है"],"answer":"भावना और हृदय का स्थान बुद्धि से बड़ा है — यह आज भी सच है","explanation":"प्रासंगिकता।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"भ्रमरगीत प्रसंग का दूसरा बड़ा संदेश क्या है?","options":["राजनीति बुरी है","प्रेम का मार्ग ज्ञान-मार्ग से कठिन भी है पर श्रेष्ठ भी","केवल योग करो","मौन रहो"],"answer":"प्रेम का मार्ग ज्ञान-मार्ग से कठिन भी है पर श्रेष्ठ भी","explanation":"दूसरा संदेश।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-03","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"पहले पद में गोपियाँ क्या स्वीकार करती हैं — पर 'गर्व' से?","options":["कि वे साधु हैं","कि उनका हृदय कृष्ण-प्रेम में डूब चुका है","कि वे राजा हैं","कि वे सोई हैं"],"answer":"कि उनका हृदय कृष्ण-प्रेम में डूब चुका है","explanation":"गर्वपूर्ण स्वीकार।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"दूसरे पद में गोपियाँ अपने मन की बात किसको नहीं कह सकीं?","options":["किसी को नहीं","कृष्ण को","उद्धव को","अपने माता-पिता को"],"answer":"कृष्ण को","explanation":"मन की बात।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-05","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"तीसरे पद की मूल शिक्षा क्या है?","options":["चुप रहो","प्रेम एकनिष्ठ हो तो वह जीवन भर का साथ देता है","धन कमाओ","लड़ो"],"answer":"प्रेम एकनिष्ठ हो तो वह जीवन भर का साथ देता है","explanation":"एकनिष्ठ प्रेम।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-06","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"चौथे पद के व्यंग्य का सबसे बड़ा निशाना क्या है?","options":["राजा का बच्चा","सत्ता-व्यवस्था का व्यक्तिगत संबंधों पर प्रभाव","कविता","शिक्षा"],"answer":"सत्ता-व्यवस्था का व्यक्तिगत संबंधों पर प्रभाव","explanation":"सत्ता का प्रभाव।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-07","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"प्रश्नात्मक शैली का प्रयोग किस पद में सबसे अधिक है?","options":["पहले","दूसरे","तीसरे","चौथे"],"answer":"चौथे","explanation":"चौथे पद में।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-07","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"सूरदास की काव्य-शैली में कौन-सा द्वैत है?","options":["सरलता और गहराई","लम्बा और छोटा","नया और पुराना","ऊँचा और नीचा"],"answer":"सरलता और गहराई","explanation":"सरल भाषा + गहरा भाव।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-SUR-08","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"'रिपु' का अर्थ क्या है?","options":["मित्र","शत्रु","गुरु","छात्र"],"answer":"शत्रु","explanation":"रिपु।"},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-HIN-SUR-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"दूसरे पद में गोपियों ने उद्धव के योग-संदेश को सहर्ष स्वीकार किया। (Gopis accepted Uddhav's yoga message)","options":["True","False"],"answer":"False","explanation":"उन्होंने अस्वीकार किया।"},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-HIN-SUR-06","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"चौथे पद में गोपियाँ कृष्ण की प्रशंसा करती हैं। (4th pad: gopis praise Krishna)","options":["True","False"],"answer":"False","explanation":"वे शिकायत करती हैं।"},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-HIN-SUR-08","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"'विप्र' और 'द्विज' दोनों शब्दों का अर्थ ब्राह्मण है। (Vipra and Dvija both mean Brahmin)","options":["True","False"],"answer":"True","explanation":"समानार्थी।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-SUR-02","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"भ्रमरगीत में कृष्ण ने अपने सखा ____ को गोपियों के पास भेजा।","answer":"उद्धव","explanation":"उद्धव।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-SUR-04","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"दूसरा पद आरम्भ होता है — 'मन की मन ही ____ रही'।","answer":"माँझ","explanation":"माँझ।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-SUR-05","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"'हमारे हरि ____ की लकरी' — तीसरा पद।","answer":"हारिल","explanation":"हारिल पक्षी।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-SUR-06","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"चौथे पद की पंक्ति है — 'हरि हैं ____ पढ़ि आए'।","answer":"राजनीति","explanation":"राजनीति।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-SUR-07","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"प्रस्तुत पाठ का मुख्य रस ____ है।","answer":"वियोग-शृंगार","explanation":"वियोग-शृंगार।"},
    # subjective
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-SUR-04","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"दूसरे पद का भावार्थ अपने शब्दों में लिखिए।","answer":"दूसरे पद में गोपियों की मनोव्यथा प्रकट होती है। वे कहती हैं — 'हमारे मन की बात मन में ही रह गई।' उन्होंने सोचा था कि कृष्ण कभी लौटेंगे और वे अपनी विरह-वेदना सुनाएँगी। पर अब उद्धव योग का संदेश लेकर आए हैं — जो उनके लिए 'ज्वलंत आग पर मरहम' की तरह अप्राप्य है। उद्धव की निर्गुण शिक्षा गोपियों के प्रेम-गुड़ की मिठास को कड़वा बना रही है। वे एकमात्र कृष्ण-प्रेम का व्रत निभा रही हैं — योग और ज्ञान उनके लिए अप्रिय हैं।","explanation":"दूसरा पद विश्लेषण।"},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-SUR-05","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"तीसरे पद के 'काले-सफेद' प्रतीक की व्याख्या कीजिए।","answer":"तीसरे पद में 'काला' और 'सफेद' दोनों रंगों का प्रतीकात्मक प्रयोग है। 'काला' श्रीकृष्ण का रंग है — जो साकार, सगुण, मूर्त ईश्वर का प्रतीक है। 'सफेद' निर्गुण-निराकार ब्रह्म का प्रतीक है — उद्धव का संदेश। गोपियाँ कहती हैं — 'हमने काले रंग से बहुत अच्छा प्रेम किया है — अब उस काले रंग को छोड़कर सफेद रंग को क्यों स्वीकार करें?' अर्थात् सगुण कृष्ण-भक्ति को छोड़कर निर्गुण ब्रह्म-उपासना अपनाना उनके लिए असम्भव है। यह प्रतीक रंगों के माध्यम से सगुण-निर्गुण के दर्शन-शास्त्रीय अंतर को सरल बनाता है।","explanation":"रंग-प्रतीक।"},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-SUR-06","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"चौथे पद में गोपियों की प्रश्नात्मक शैली का क्या महत्त्व है?","answer":"चौथे पद में गोपियाँ एक के बाद एक प्रश्न उठाती हैं — 'जिनके मन में हमारा प्रेम था, वे अब राजनीतिज्ञ कैसे बन गए? जिनकी बंसी की धुन सुनते ही हम सब कुछ छोड़ देती थीं, वे अब हमें भुला कैसे सकते हैं?' इस शैली का तीन तरह का महत्त्व है — (१) सजीवता: प्रश्न पाठक को सीधे संबोधित करते हैं, संवाद जीवंत बनाते हैं। (२) मार्मिकता: हर प्रश्न में पीड़ा छिपी है — गोपियों की वेदना सीधे हमारे हृदय तक पहुँचती है। (३) चुनौती: प्रश्न केवल जिज्ञासा नहीं — वे राजनीति और सत्ता-प्रेम पर सूक्ष्म व्यंग्य भी हैं।","explanation":"प्रश्नात्मक शैली का महत्त्व।"},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-SUR-09","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"सूरदास के पदों में मानवीय भावनाओं के कौन-कौन से रूप दिखाई देते हैं?","answer":"सूरदास के चारों पदों में अनेक मानवीय भावनाओं के रूप दिखाई देते हैं — (१) प्रेम — गोपियों का अनन्य कृष्ण-प्रेम; (२) विरह — कृष्ण के बिछुड़ने पर गोपियों की वेदना; (३) अभिमान — अपने प्रेम-व्रत पर गर्व; (४) निराशा — कृष्ण के न लौटने पर; (५) व्यंग्य — उद्धव की निर्लिप्तता और कृष्ण की राजनीति पर; (६) समर्पण — हारिल पक्षी जैसा एकनिष्ठ; (७) शिकायत — कृष्ण से; (८) धैर्य — पर्याप्त मात्रा में, पर अंत में टूटता हुआ। यह भावना-समृद्धता ही सूरदास के पदों को सार्वभौमिक बनाती है।","explanation":"मानवीय भावनाओं की समृद्धि।"},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-SUR-08","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"पाठ के सात कठिन शब्दों के अर्थ संक्षेप में लिखिए।","answer":"(१) पुरइन-पात — कमल का पत्ता। (२) दागी — डूबा हुआ; प्रभावित। (३) ब्याधि — रोग, बीमारी। (४) ऊधो — उद्धव का प्रचलित रूप। (५) पाहन — पत्थर, पाषाण। (६) उर अंतरगत — हृदय के अंदर। (७) हारिल की लकरी — एकनिष्ठ समर्पण का प्रतीक। (८) मानहुँ — जैसे, मानो। (९) रिपु — शत्रु। (१०) तपोबल — तप का बल।","explanation":"शब्दार्थ।"},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-HIN-SUR-04","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"दूसरे पद का विस्तार से विवेचन कीजिए — विषय, भाव, और शिल्प।","answer":"विषय-वस्तु — दूसरे पद की प्रथम पंक्ति है — 'मन की मन ही माँझ रही'। गोपियाँ बताती हैं कि उनके मन की बात मन में ही रह गई। उनकी आशा थी कि कृष्ण कभी लौटेंगे और वे विरह सुनाएँगी, परंतु अब उद्धव योग-संदेश लेकर आए हैं — जो उनके लिए 'ज्वलंत आग पर मरहम' की तरह अप्राप्य है। उद्धव का उपदेश 'गुड़-गोबर' की तरह — मीठी प्रेम-गुड़ को कड़वा बना रहा है। भाव — मुख्य भाव है निराशा और कृष्ण के प्रति शिकायत। साथ ही उद्धव के उपदेश का अस्वीकरण — 'हम तो एक ही प्रेम का व्रत निभा रही हैं — कृष्ण-प्रेम का।' पद में वियोग का दर्द, अधूरी आशा का खिन्नता, और एकनिष्ठ प्रेम का अभिमान — सब एक साथ दिखाई देते हैं। शिल्प — (१) सरल अवधी ब्रजभाषा। (२) रूपक — 'ज्वलंत आग पर मरहम'। (३) अनुप्रास — 'मन की मन माँझ'। (४) कहावत-योजना — 'गुड़-गोबर'। (५) संगीतात्मक लय। निष्कर्ष — दूसरा पद मानवीय निराशा और एकनिष्ठ प्रेम के द्वंद्व का सशक्त चित्रण है।","explanation":"दूसरा पद विवेचन।"},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-HIN-SUR-06","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"चौथे पद के माध्यम से गोपियाँ क्या कहना चाहती हैं? व्यंग्य और शिकायत का संतुलन कैसे बनाती हैं?","answer":"चौथा पद सूरदास की काव्य-कुशलता का चरम है। यहाँ गोपियाँ — व्यंग्य और शिकायत के सूक्ष्म संतुलन से — कृष्ण के बदलाव पर अपनी प्रतिक्रिया देती हैं। मुख्य कथ्य: कृष्ण मथुरा जाकर 'राजनीति पढ़ि आए हैं' — अर्थात् राज्य-संचालन की कलाएँ सीखकर अब वे प्रेम के सरल मार्ग से भटक गए हैं। पहले वे प्रेम-संदेश भेजते थे, अब केवल राजनीतिक संदेश। तीन प्रकार की प्रतिक्रियाएँ हैं — (१) व्यंग्य कृष्ण पर: 'अब वे राजा हो गए हैं — जो हमारे थे, वे क्या हमारे ही रहेंगे?' यह व्यंग्य प्रेमिका के तीखेपन का है। (२) शिकायत: 'जिनकी बंसी सुनकर हम सब कुछ छोड़ देती थीं, वे हमें भुला कैसे सकते हैं?' यह शिकायत हृदय की पीड़ा का है। (३) सामाजिक टीका: सत्ता और प्रेम का संबंध — जब व्यक्ति राजा बनता है, क्या वह सरल मानवीय भावनाओं से दूर हो जाता है? यह सार्वभौमिक प्रश्न है। संतुलन का शिल्प — गोपियाँ क्रोध से नहीं भर जातीं; वे शिकायत-व्यंग्य के मिश्रण से बात करती हैं। प्रश्नात्मक शैली से उन्होंने आक्रोश को संयत किया। 'हम जानती हैं कि वे राजनीति में डूब चुके हैं' — इस वाक्य में उन्होंने कृष्ण पर सीधा आरोप नहीं लगाया, बल्कि अपनी समझ प्रस्तुत की। आधुनिक प्रासंगिकता — आज के राजनेताओं और सेलिब्रिटीज पर भी यह व्यंग्य प्रासंगिक है। जब व्यक्ति सत्ता-शिखर पर पहुँचता है, क्या वह अपने पुराने रिश्तों को निभा पाता है? निष्कर्ष — चौथा पद व्यंग्य और शिकायत का अद्भुत मिश्रण है। गोपियाँ साधारण प्रेमिकाएँ नहीं — वे जीवन-भर के अनुभव की संवेदी निरीक्षिकाएँ हैं।","explanation":"चौथा पद विस्तार से।"},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-HIN-SUR-09","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"सूरदास के पदों की आधुनिक प्रासंगिकता पर चर्चा कीजिए।","answer":"सूरदास के ये चार पद ५०० वर्ष पुराने हैं, परंतु आज भी उतने ही प्रासंगिक हैं जितने उनके लिखे जाते समय। (१) प्रेम बनाम तर्क — आज के बुद्धिवादी और तर्क-प्रधान युग में सूरदास का संदेश कि 'हृदय बुद्धि से बड़ा है' और भी महत्त्वपूर्ण है। हम सबके जीवन में ऐसे क्षण आते हैं जब हमारा हृदय किसी से प्रेम करता है और कोई हमें 'तर्क' का उपदेश देता है — गोपी-उद्धव संवाद हमारी कहानी है। (२) एकनिष्ठ समर्पण की शक्ति — हारिल पक्षी की उपमा 'एकनिष्ठ समर्पण' का संदेश देती है। आज के विचलित, बहु-कार्यी, सोशल-मीडिया-व्यस्त समाज में जहाँ ध्यान-केन्द्रण एक सेकंड में टूट जाता है — हारिल की निरंतरता एक मूल्यवान आदर्श है। (३) वियोग की वेदना — आधुनिक शहरों में परिवार से दूर रहना, प्रिय से वियुक्त होना — यह आज भी जीवन का हिस्सा है। गोपियों का दर्द हर वियोगी का दर्द है। (४) सत्ता-प्रेम का व्यंग्य — 'हरि हैं राजनीति पढ़ि आए' का व्यंग्य आज के राजनेताओं, सेलिब्रिटीज, बड़े पदों पर पहुँचे लोगों पर भी लागू होता है। जब व्यक्ति 'राजा' बनता है, क्या वह पुराने सम्बन्धों को निभा पाता है? (५) ज्ञान बनाम भक्ति — आज भी वैज्ञानिक तर्क और आध्यात्मिक भावना के बीच यह विमर्श चलता है। सूरदास का संतुलित संदेश है कि दोनों की अपनी जगह है, परंतु जब बात मनुष्य के हृदय की हो — भक्ति श्रेष्ठ है। (६) काव्य का संगीत — आज भी ये पद गाये जाते हैं; लोक-संगीत और शास्त्रीय संगीत दोनों में सूरदास के पद हैं। यह संगीतात्मकता अमूल्य है। (७) सामाजिक टीका की कला — सूरदास ने व्यंग्य के माध्यम से कोमल पर तीखी सामाजिक टीका की — आज के पत्रकारों और सोशल-मीडिया लेखकों के लिए यह आदर्श है। निष्कर्ष — सूरदास का काव्य न केवल भक्ति-कविता है, बल्कि मानवीय अनुभव का एक कालातीत दर्पण है। उनका संदेश आज भी ताज़ा है।","explanation":"आधुनिक प्रासंगिकता।"},
]

# ===== ch238 (राम-लक्ष्मण-परशुराम) — need +45 obj, +19 subj =====
EXTRA_238 = [
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"तुलसीदास का जन्म-स्थान कहाँ माना जाता है?","options":["वाराणसी","राजापुर / सोरों","मथुरा","अयोध्या"],"answer":"राजापुर / सोरों","explanation":"उत्तर प्रदेश में।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"तुलसीदास की 'विनयपत्रिका' किस भाषा में है?","options":["संस्कृत","ब्रजभाषा","अवधी","मैथिली"],"answer":"ब्रजभाषा","explanation":"ब्रजभाषा।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"रामचरितमानस किसका अवधी पुनराख्यान है?","options":["भगवद्गीता","वाल्मीकि-रामायण","महाभारत","पुराण"],"answer":"वाल्मीकि-रामायण","explanation":"वाल्मीकि-रामायण का अवधी रूप।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-01","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"रामचरितमानस के अंतिम काण्ड का नाम क्या है?","options":["अरण्यकाण्ड","सुन्दरकाण्ड","लंकाकाण्ड","उत्तरकाण्ड"],"answer":"उत्तरकाण्ड","explanation":"सात काण्डों में अंतिम।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-02","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"राम धनुष-यज्ञ में किसकी आज्ञा से गए थे?","options":["जनक","विश्वामित्र","दशरथ","कौशल्या"],"answer":"विश्वामित्र","explanation":"विश्वामित्र की आज्ञा से।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-02","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"धनुष कितनी देर के लिए राम के हाथ में रहा?","options":["कुछ क्षण","एक दिन","एक सप्ताह","कभी नहीं"],"answer":"कुछ क्षण","explanation":"प्रत्यंचा चढ़ाते समय टूटा।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-02","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"शिव-धनुष का प्रत्यंचा चढ़ाने का परिणाम क्या हुआ?","options":["राम विजयी हुए","धनुष टूट गया और सीता-राम विवाह सम्भव हुआ","धनुष आकाश में उड़ गया","कुछ नहीं हुआ"],"answer":"धनुष टूट गया और सीता-राम विवाह सम्भव हुआ","explanation":"विवाह की राह।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-03","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"परशुराम की माता का क्या नाम था?","options":["सीता","रेणुका","देवकी","कौशल्या"],"answer":"रेणुका","explanation":"रेणुका।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-03","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"क्षत्रिय-संहार के लिए परशुराम का मुख्य कारण क्या था?","options":["भूख","क्षत्रिय राजा अहंकारी और अधर्मी हो गए थे","मनोरंजन","राज्य पाने की इच्छा"],"answer":"क्षत्रिय राजा अहंकारी और अधर्मी हो गए थे","explanation":"धर्म-स्थापना का कारण।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"राम परशुराम के लिए कौन-सा मधुर सम्बोधन प्रयोग करते हैं?","options":["राजा","प्रभु","बच्चा","मित्र"],"answer":"प्रभु","explanation":"'हे प्रभो'।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"राम के स्वर का स्वरूप कैसा है?","options":["कठोर","मधुर, विनय-पूर्ण","अस्पष्ट","ऊँचा"],"answer":"मधुर, विनय-पूर्ण","explanation":"मधुर वाणी।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-05","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"लक्ष्मण ने धनुष की उम्र कैसी बताई?","options":["नया","पुरानी, बाल्यकाल जैसी","मध्यम","अनन्त"],"answer":"पुरानी, बाल्यकाल जैसी","explanation":"छोटी पुरानी लकड़ी।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-05","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"लक्ष्मण ने परशुराम को क्या बताया कि वे लड़ाई से बच रहे हैं?","options":["कि उन्हें भूख है","कि वे बड़ों का सम्मान कर रहे हैं","कि उन्हें कुछ नहीं आता","कि वे डरते हैं"],"answer":"कि वे बड़ों का सम्मान कर रहे हैं","explanation":"मर्यादा का तर्क।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-05","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"लक्ष्मण ने किसके धर्म-विरोध की टिप्पणी की?","options":["राजा का","ब्राह्मण-धर्म और क्रोध का","गुरु-शिष्य का","धन का"],"answer":"ब्राह्मण-धर्म और क्रोध का","explanation":"धर्म-संगति की टीका।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-06","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"लक्ष्मण की वाक्पटुता में कौन-सा गुण विशेष रूप से दिखता है?","options":["भय","तर्क और साहस का संगम","कायरता","गूँगापन"],"answer":"तर्क और साहस का संगम","explanation":"तर्क + साहस।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-07","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"विश्वामित्र ने परशुराम को क्या समझाया?","options":["कि राम युवराज हैं","कि राम विष्णु के अवतार हैं","कि राम क्रोधी हैं","कि राम कौन हैं नहीं पता"],"answer":"कि राम विष्णु के अवतार हैं","explanation":"दिव्यता।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-07","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"परशुराम और राम दोनों किसके अवतार हैं?","options":["शिव","ब्रह्मा","विष्णु","इन्द्र"],"answer":"विष्णु","explanation":"दोनों विष्णु के।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-07","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"परशुराम का क्रोध शान्त होने के बाद उन्होंने राम को क्या दिया?","options":["राज्य","अपना धनुष-बाण","फरसा","आशीर्वाद"],"answer":"अपना धनुष-बाण","explanation":"पहचान का प्रतीक।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-08","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"राम और लक्ष्मण के बीच मुख्य भिन्नता क्या है?","options":["रंग","राम मध्यम मार्ग के, लक्ष्मण सीधी टक्कर के","आयु","परिवार"],"answer":"राम मध्यम मार्ग के, लक्ष्मण सीधी टक्कर के","explanation":"दोनों की भिन्न शैली।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-08","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"राम और लक्ष्मण मिलकर क्या बनाते हैं?","options":["एक राजा","एक पूर्ण व्यक्तित्व — विनय और तेज दोनों","एक धनुष","एक मन्त्र"],"answer":"एक पूर्ण व्यक्तित्व — विनय और तेज दोनों","explanation":"पूरकता।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"पाठ में 'क्रोध की अग्नि' कौन-सा अलंकार है?","options":["उपमा","रूपक","अनुप्रास","श्लेष"],"answer":"रूपक","explanation":"क्रोध को अग्नि कहना।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"'इक्कीस बार पृथ्वी का संहार' किस अलंकार का उदाहरण है?","options":["उपमा","अतिशयोक्ति","अनुप्रास","श्लेष"],"answer":"अतिशयोक्ति","explanation":"बढ़ाकर कहना।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"तुलसीदास के काव्य की लोक-प्रियता का मुख्य कारण क्या है?","options":["कठिन भाषा","सरल भाषा + संगीतात्मकता + भक्ति","लम्बाई","दुर्लभता"],"answer":"सरल भाषा + संगीतात्मकता + भक्ति","explanation":"लोक-प्रियता।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":2,"question":"पाठ में हास्य-रस किस पात्र की वाणी से उत्पन्न होता है?","options":["राम की","लक्ष्मण की व्यंग्यात्मक वाणी से","परशुराम की","विश्वामित्र की"],"answer":"लक्ष्मण की व्यंग्यात्मक वाणी से","explanation":"लक्ष्मण के व्यंग्य से।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-10","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"पाठ का मुख्य आधुनिक संदेश क्या है?","options":["केवल पुरानी कहानी","विनय और तर्क के संगम से ही समाज सम्भव","केवल मनोरंजन","केवल भक्ति"],"answer":"विनय और तर्क के संगम से ही समाज सम्भव","explanation":"राम+लक्ष्मण = आदर्श।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-10","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"परशुराम के चरित्र से क्या सीख मिलती है?","options":["कि क्रोध अच्छा है","कि गलती स्वीकारना ही महान आत्मा का गुण है","कि लड़ना चाहिए","कि भागना चाहिए"],"answer":"कि गलती स्वीकारना ही महान आत्मा का गुण है","explanation":"पहचानकर सम्मान।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"'सुजसु' का अर्थ क्या है?","options":["अच्छा यश","दुःख","भोजन","रंग"],"answer":"अच्छा यश","explanation":"सुनाम।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"'प्रचण्ड' का अर्थ क्या है?","options":["शान्त","उग्र, भयानक","छोटा","मीठा"],"answer":"उग्र, भयानक","explanation":"प्रचण्ड।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"राम के व्यवहार का मूल आधार क्या है?","options":["क्रोध","धैर्य और मर्यादा","भय","अहंकार"],"answer":"धैर्य और मर्यादा","explanation":"मर्यादा-पुरुषोत्तम।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-05","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":2,"question":"लक्ष्मण ने 'बाल-धनुष' कहकर क्या प्रकट किया?","options":["कि वे बच्चे हैं","कि धनुष का महत्त्व उतना नहीं जितना परशुराम बना रहे हैं","कि वे हँसी-मज़ाक करते हैं","कि वे लड़ना चाहते हैं"],"answer":"कि धनुष का महत्त्व उतना नहीं जितना परशुराम बना रहे हैं","explanation":"महत्त्व का मखौल।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-08","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"राम और लक्ष्मण में कौन-सी समानता है?","options":["दोनों राजा हैं","दोनों सत्यनिष्ठ क्षत्रिय राजकुमार हैं","दोनों भगवान हैं","दोनों ब्राह्मण हैं"],"answer":"दोनों सत्यनिष्ठ क्षत्रिय राजकुमार हैं","explanation":"समानताएँ।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-10","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"पाठ का सबसे मूल्यवान संदेश क्या है?","options":["केवल लड़ो","सच्ची शक्ति विनय और संयम में है, क्रोध में नहीं","केवल हँसो","केवल बैठो"],"answer":"सच्ची शक्ति विनय और संयम में है, क्रोध में नहीं","explanation":"मुख्य संदेश।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"पाठ में मुख्य रस के साथ कौन-सा पूरक रस है?","options":["भयानक","हास्य-रस (लक्ष्मण के व्यंग्य से)","रौद्र","अद्भुत"],"answer":"हास्य-रस (लक्ष्मण के व्यंग्य से)","explanation":"बहुरसी।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":1,"question":"मानस की रचना तुलसीदास ने कहाँ की?","options":["वाराणसी (काशी) में","अयोध्या में","मथुरा में","दिल्ली में"],"answer":"वाराणसी (काशी) में","explanation":"काशी में रचना।"},
    {"type":"MCQ","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"रामचरितमानस की रचना का प्रारम्भ-समय क्या है?","options":["१४८०","१५७४ ई.","१६५०","१७२३"],"answer":"१५७४ ई.","explanation":"१५७४ में आरम्भ।"},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-HIN-RLP-04","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"राम परशुराम के सामने क्रोध से उत्तर देते हैं। (Ram angrily answers Parashuram)","options":["True","False"],"answer":"False","explanation":"वे विनम्रता से उत्तर देते हैं।"},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-HIN-RLP-05","difficulty":"EASY","cognitive_level":"UNDERSTAND","marks":1,"question":"लक्ष्मण ने परशुराम पर शारीरिक हमला किया। (Lakshman physically attacked Parashuram)","options":["True","False"],"answer":"False","explanation":"केवल वाणी से।"},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-HIN-RLP-08","difficulty":"EASY","cognitive_level":"ANALYZE","marks":1,"question":"राम और लक्ष्मण के चरित्र पूरक हैं। (Ram and Lakshman's characters are complementary)","options":["True","False"],"answer":"True","explanation":"पूरकता।"},
    {"type":"TRUE_FALSE","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"प्रस्तुत संवाद में हास्य-रस भी है। (The dialogue also has hasya rasa)","options":["True","False"],"answer":"True","explanation":"लक्ष्मण के व्यंग्य से।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-RLP-04","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"राम परशुराम को 'हे ____' कहकर सम्बोधित करते हैं।","answer":"प्रभो","explanation":"प्रभो।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-RLP-05","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"लक्ष्मण ने धनुष को 'छोटी-सी पुरानी ____' बताया।","answer":"लकड़ी","explanation":"लकड़ी।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-RLP-07","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"विश्वामित्र ने कहा कि राम स्वयं भगवान ____ के अवतार हैं।","answer":"विष्णु","explanation":"विष्णु।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"प्रस्तुत संवाद में मुख्य रस ____ है।","answer":"वीर","explanation":"वीर-रस।"},
    {"type":"FILL_BLANK","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"EASY","cognitive_level":"REMEMBER","marks":1,"question":"रामचरितमानस की भाषा ____ है।","answer":"अवधी","explanation":"अवधी।"},
    # subjective for ch238
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-RLP-04","difficulty":"MEDIUM","cognitive_level":"UNDERSTAND","marks":3,"question":"राम के व्यवहार से कौन-सा संदेश मिलता है?","answer":"राम का व्यवहार 'मर्यादा-पुरुषोत्तम' का आदर्श है। क्रोधी परशुराम के सामने भी वे शान्त, मधुर वाणी से बोलते हैं — स्वयं को 'दास' कहकर परम विनय प्रकट करते हैं। वे लक्ष्मण की कठोर वाणी का भी समर्थन नहीं करते। संदेश — (१) सच्ची शक्ति विनय और संयम में है, क्रोध में नहीं। (२) बड़े-छोटे का सम्मान करना संस्कार है। (३) महान आत्मा भीषण क्रोधी के सामने भी मर्यादा नहीं छोड़ती। (४) धैर्य ही असली पराक्रम है। राम का व्यवहार आज के तेज-गति युग में 'धैर्य' की मूल्यवान सीख है।","explanation":"राम का संदेश।"},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-RLP-06","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"लक्ष्मण के व्यंग्य का मूल्यांकन कीजिए — क्या उन्हें इतनी तीखी बातें कहनी चाहिए थीं?","answer":"लक्ष्मण का व्यंग्य दो दृष्टियों से देखा जा सकता है। पक्ष में — (१) परशुराम का क्रोध अनियंत्रित था; यदि कोई उन्हें न रोकता, तो हिंसा हो सकती थी। (२) लक्ष्मण ने तर्क का सहारा लिया — 'ब्राह्मण-धर्म क्रोध से उलटा है' — यह सत्य है। (३) उन्होंने राम की रक्षा की और अहंकार को चुनौती दी। विरुद्ध — (१) परशुराम ब्राह्मण और गुरुजन हैं; उनके सामने इतनी तीखी बातें कहना मर्यादा-भंग है। (२) इससे क्रोध और बढ़ा। (३) राम को विनय से जो प्रभाव बनाना था, उसे लक्ष्मण की कठोरता ने कमज़ोर किया। निष्कर्ष — लक्ष्मण की वाणी में सत्य था, परंतु शैली में मर्यादा कम थी। आदर्श यह होता कि वे राम के समान विनय से ही अपनी बात कहते। पर लक्ष्मण का चरित्र इसी 'युवा-तेज + तर्क' का है — और यही पाठ की सजीवता का स्रोत भी है।","explanation":"लक्ष्मण का मूल्यांकन।"},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-RLP-07","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"विश्वामित्र की भूमिका का महत्त्व समझाइए।","answer":"विश्वामित्र की भूमिका इस संवाद में निर्णायक है। (१) मध्यस्थ — जब परशुराम और लक्ष्मण के बीच टकराव बढ़ रहा था, विश्वामित्र ने बीच में आकर शान्ति की राह खोली। (२) ज्ञानी — उन्होंने परशुराम को राम की दिव्यता बतायी — 'राम स्वयं विष्णु के अवतार हैं'। यह तथ्य ही परशुराम का क्रोध शान्त करने में सबसे प्रभावी रहा। (३) सेतु — उन्होंने दो विरोधी पक्षों के बीच पुल बनाया। (४) समय का विवेक — विश्वामित्र ने सही समय पर हस्तक्षेप किया — पहले लक्ष्मण की वाणी सुनी, फिर परशुराम का क्रोध देखा, और जब लगा कि अब बात बिगड़ सकती है — तभी बोले। उनकी भूमिका दर्शाती है कि बुद्धिमान और तपस्वी व्यक्ति का काम विवादों को हिंसा में बदलने से रोकना है।","explanation":"विश्वामित्र की भूमिका।"},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-RLP-08","difficulty":"MEDIUM","cognitive_level":"ANALYZE","marks":3,"question":"राम और लक्ष्मण की पूरकता पर प्रकाश डालिए।","answer":"राम और लक्ष्मण के चरित्र विरोधी से दिखते हैं — पर वास्तव में वे पूरक हैं। (१) राम — विनय, संयम, धैर्य, मधुरता; लक्ष्मण — तेज, साहस, तर्क, वाक्पटुता। (२) राम मधुर वाणी से कहते हैं — परशुराम का क्रोध शान्त करते हैं; लक्ष्मण तीखी वाणी से कहते हैं — परशुराम के अहंकार को चुनौती देते हैं। (३) राम मध्यम मार्ग; लक्ष्मण सीधी टक्कर। (४) यदि केवल राम होते — परशुराम का अहंकार बना रहता; यदि केवल लक्ष्मण होते — हिंसा हो सकती थी। दोनों मिलकर — संयम + तेज, विनय + तर्क — एक पूर्ण व्यक्तित्व बनाते हैं। यह संदेश है कि आदर्श समाज में दोनों गुणों की आवश्यकता है — कोई एक अकेला अधूरा है।","explanation":"पूरकता।"},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-RLP-09","difficulty":"MEDIUM","cognitive_level":"REMEMBER","marks":3,"question":"पाठ में प्रयुक्त मुख्य रसों का संक्षिप्त परिचय दीजिए।","answer":"प्रस्तुत पाठ बहुरसी है। (१) वीर-रस — मुख्य रस; परशुराम का क्रोध और लक्ष्मण की वाक्पटुता दोनों वीर हैं। (२) हास्य-रस — लक्ष्मण के व्यंग्यात्मक कथनों से, विशेष रूप से 'छोटी-सी पुरानी लकड़ी' और 'बाल-धनुष' की बातें। (३) करुण-रस — राम की विनय में करुणा का स्पर्श; गुरुजन-सम्मान का भाव। (४) शान्त-रस — अंत में विश्वामित्र की मध्यस्थता से शान्ति आती है। यह 'बहुरसी' संरचना तुलसीदास की काव्य-शक्ति का अद्भुत प्रमाण है — एक ही प्रसंग में चार रसों का संगम।","explanation":"रस-योजना।"},
    {"type":"SHORT_ANSWER","outcome_code":"10-CBSE-HIN-RLP-10","difficulty":"MEDIUM","cognitive_level":"EVALUATE","marks":3,"question":"पाठ की आधुनिक प्रासंगिकता पर टिप्पणी कीजिए।","answer":"पाठ का सन्देश आज भी पूर्णतया प्रासंगिक है। (१) क्रोध-प्रबंधन — आज की तेज, तनावपूर्ण दुनिया में जहाँ रोज़ की कोई-न-कोई बात पर लोग आपा खो देते हैं — राम का संयम एक मूल्यवान उदाहरण है। (२) सत्य कहने का साहस — लक्ष्मण का चरित्र आज के 'व्हिसलब्लोअर' और सामाजिक सुधारकों के लिए आदर्श है — अन्याय के सामने चुप रहना दुर्बलता है। (३) मध्यस्थता — विश्वामित्र की भूमिका आज के राजनयिकों, मध्यस्थों, और शान्ति-प्रयासकर्ताओं के लिए आदर्श है। (४) धर्म-संगति — परशुराम के द्वैत से सीख कि अपने धर्म (पेशे, भूमिका) के अनुरूप व्यवहार करना चाहिए — एक भूमिका में रहते हुए दूसरी भूमिका के गुण-दोष लाना उचित नहीं। (५) अहंकार-निवारण — परशुराम का अंत में सत्य को पहचानना दर्शाता है कि गलती स्वीकारना ही महान आत्मा का गुण है। ये सभी सीख आज भी अमूल्य हैं।","explanation":"आधुनिक प्रासंगिकता।"},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-HIN-RLP-03","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"परशुराम के चरित्र-द्वैत (ब्राह्म-तेज + क्षात्र-तेज) पर विस्तार से चर्चा कीजिए।","answer":"परशुराम का चरित्र हिन्दी साहित्य में 'ब्राह्म-तेज' और 'क्षात्र-तेज' के मिलन का सर्वोत्तम उदाहरण है। ब्राह्म-तेज — परशुराम तपस्वी ब्राह्मण हैं — जमदग्नि ऋषि के पुत्र, शिव के परम भक्त। उन्होंने कठोर तपस्या की है। उनके पास तपोबल है, मन्त्र-शक्ति है, और शिव-कृपा है। ब्राह्मण के परम्परागत गुण — शान्ति, क्षमा, ज्ञान, अहिंसा — उन्हें परिवारिक और शैक्षिक पृष्ठभूमि से प्राप्त हुए हैं। क्षात्र-तेज — पर परशुराम केवल पुजारी नहीं — वे एक प्रसिद्ध योद्धा भी हैं। उनके हाथ में सदैव फरसा रहता है। पौराणिक कथाओं के अनुसार उन्होंने इक्कीस बार पृथ्वी को क्षत्रियों से रहित किया — यह क्षत्रिय-वीर का काम है। उनका क्रोध भी अग्नि-समान है। द्वैत का स्रोत — यह द्वैत आकस्मिक नहीं — पौराणिक कथा के अनुसार, जब राजा कार्तवीर्यार्जुन (सहस्रबाहु) ने उनके पिता का वध किया, तब परशुराम का ब्राह्म-शान्ति टूटी और क्षात्र-तेज जागृत हुआ। इस घटना ने उनके चरित्र में न्याय-स्थापना का दायित्व बोध जगा दिया — और तब से वे जब भी अधर्म देखते हैं, क्रुद्ध हो जाते हैं। प्रस्तुत पाठ में अभिव्यक्ति — पाठ में परशुराम के दोनों रूप दिखाई देते हैं। पहले — उग्र क्षत्रिय रूप जब वे क्रोध से भरकर सभा में आते हैं, फरसा उठाये दौड़ते हैं। बाद में — शान्त ब्राह्मण रूप जब विश्वामित्र की मध्यस्थता से वे राम की दिव्यता को पहचानते हैं और शान्तिपूर्वक धनुष-बाण देकर विदा लेते हैं। द्वैत का संदेश — परशुराम का चरित्र हमें सिखाता है कि (१) एक ही व्यक्ति में अनेक गुण हो सकते हैं — हम केवल एक रंग के नहीं होते। (२) क्रोध और शान्ति दोनों आवश्यक हैं — पर सही समय पर। (३) महान आत्मा अपने 'द्वैत' को पहचानती है और उसे संयम से प्रयुक्त करती है। (४) ब्राह्मण-धर्म और क्षत्रिय-धर्म दोनों परस्पर पूरक हो सकते हैं। आधुनिक संदर्भ — आज के समाज में हम एक ही व्यक्ति से अनेक भूमिकाएँ अपेक्षा करते हैं — व्यापारी, माता-पिता, समाज-सुधारक, साहित्यकार। परशुराम का चरित्र दर्शाता है कि यह सम्भव है — पर हर भूमिका के समय अनुरूप गुण-प्रयोग आवश्यक है।","explanation":"परशुराम का द्वैत।"},
    {"type":"LONG_ANSWER","outcome_code":"10-CBSE-HIN-RLP-08","difficulty":"HARD","cognitive_level":"EVALUATE","marks":5,"question":"प्रस्तुत संवाद में चरित्र-चित्रण की कौन-कौन सी विशेषताएँ हैं?","answer":"तुलसीदास के 'राम-लक्ष्मण-परशुराम संवाद' में चरित्र-चित्रण की पराकाष्ठा है। चार पात्रों — राम, लक्ष्मण, परशुराम, विश्वामित्र — के चरित्र इतने स्पष्ट और जीवंत हैं कि पाठक उन्हें अपने सामने देखता है। विशेषताएँ — (१) पात्रों की अलग-अलग 'आवाज़' — प्रत्येक पात्र की वाणी का अपना विशिष्ट रूप है। राम — मधुर, विनय-पूर्ण, छोटे वाक्य; लक्ष्मण — तीखे, व्यंग्य-पूर्ण, तर्कसंगत प्रश्न; परशुराम — गरजते हुए, अहंकार-पूर्ण, अतिशयोक्ति-पूर्ण; विश्वामित्र — शान्त, बुद्धिमान, संयत। एक ही पंक्ति पढ़कर पाठक तुरन्त बता सकता है कौन बोल रहा है। (२) चरित्र-विकास — संवाद के दौरान पात्र विकसित होते हैं। परशुराम का क्रोध बढ़ता-घटता है — विकास का स्पष्ट चित्रण। राम स्थिर रहते हैं — स्थिरता भी एक चरित्र-विशेषता। लक्ष्मण की वाक्पटुता परशुराम के क्रोध के साथ बढ़ती है — संवादात्मक विकास। (३) आंतरिक-बाहरी संगति — हर पात्र का बाहरी व्यवहार उसके आंतरिक गुणों से मेल खाता है। राम का बाहरी विनय आंतरिक संयम से जन्मा है; लक्ष्मण का व्यंग्य उसके युवा-तेज से। (४) नाटकीय जीवन्तता — पात्र मूर्तियाँ नहीं, सजीव हैं। उनकी मुस्कुराहट, उनके फरसे का तेज, उनकी आँखों की चमक — सब दिखाई देती है। (५) पूरकता — चार पात्र एक-दूसरे के पूरक हैं — कोई एक अकेला पाठ को पूर्ण नहीं कर सकता। राम का संयम लक्ष्मण के तेज को संतुलित करता है; परशुराम का क्रोध विश्वामित्र की शान्ति से शान्त होता है। (६) सार्वभौमिकता — चारों चरित्र मात्र पौराणिक नहीं, मानवीय हैं। हम सबमें कुछ राम है, कुछ लक्ष्मण, कुछ परशुराम, कुछ विश्वामित्र। (७) धर्म-नीति का संगम — हर पात्र अपने धर्म (भूमिका) का प्रतिनिधित्व करता है — राजपुत्र, अनुज, ऋषि-योद्धा, गुरु। तुलसीदास हर भूमिका के मूल्यों को सजीव बनाते हैं। (८) सूक्ष्म मनोविज्ञान — पात्रों के विचारों और भावों का सूक्ष्म चित्रण है। परशुराम के क्रोध के पीछे उनका अहंकार और शिव-भक्ति दोनों दिखते हैं; लक्ष्मण के व्यंग्य के पीछे राम-रक्षा का भाव दिखता है। निष्कर्ष — तुलसीदास का चरित्र-चित्रण इतना प्रभावी है कि पाँच शताब्दियों के बाद भी ये पात्र हमारे लिए जीवित हैं। यह उनकी काव्य-कला की सर्वोच्च उपलब्धि है।","explanation":"चरित्र-चित्रण की विशेषताएँ।"},
]


def main():
    db = SessionLocal()
    try:
        n237 = insert_for_chapter(db, 237, EXTRA_237)
        print(f"  ch237: inserted {n237} new questions (skipped {len(EXTRA_237) - n237} as duplicates)")
        n238 = insert_for_chapter(db, 238, EXTRA_238)
        print(f"  ch238: inserted {n238} new questions (skipped {len(EXTRA_238) - n238} as duplicates)")
    finally:
        db.close()


if __name__ == "__main__":
    main()
